window.meta = {
  "states": [
    {"usa": [
      {"name":"Alaska"},
      {"name":"Alabama"},
      {"name":"Arkansas"},
      {"name":"Arizona"},
      {"name":"California"},
      {"name":"Colorado"},
      {"name":"Connecticut"},
      {"name":"Delaware"},
      {"name":"Florida"},
      {"name":"Georgia"},
      {"name":"Hawaii"},
      {"name":"Iowa"},
      {"name":"Idaho"},
      {"name":"Illinois"},
      {"name":"Indiana"},
      {"name":"Kansas"},
      {"name":"Kentucky"},
      {"name":"Louisiana"},
      {"name":"Massachusetts"},
      {"name":"Maryland"},
      {"name":"Maine"},
      {"name":"Michigan"},
      {"name":"Minnesota"},
      {"name":"Missouri"},
      {"name":"Mississippi"},
      {"name":"Montana"},
      {"name":"North Carolina"},
      {"name":"North Dakota"},
      {"name":"Nebraska"},
      {"name":"New Hampshire"},
      {"name":"New Jersey"},
      {"name":"New Mexico"},
      {"name":"Nevada"},
      {"name":"New York"},
      {"name":"Ohio"},
      {"name":"Oklahoma"},
      {"name":"Oregon"},
      {"name":"Pennsylvania"},
      {"name":"Rhode Island"},
      {"name":"South Carolina"},
      {"name":"South Dakota"},
      {"name":"Tennessee"},
      {"name":"Texas"},
      {"name":"Utah"},
      {"name":"Virginia"},
      {"name":"Vermont"},
      {"name":"Washington"},
      {"name":"Wisconsin"},
      {"name":"West Virginia"},
      {"name":"Wyoming"}
      ]
    }
  ],
  "countries": [
    {"name":"Afghanistan","abbrev":"afg"},
    {"name":"Angola","abbrev":"ang"},
    {"name":"Albania","abbrev":"alb"},
    {"name":"Andorra","abbrev":"and"},
    {"name":"United Arab Emirates","abbrev":"uae"},
    {"name":"Argentina","abbrev":"arg"},
    {"name":"Armenia","abbrev":"arm"},
    {"name":"Antarctica","abbrev":"ant"},
    {"name":"Antigua and Barb.","abbrev":"antb"},
    {"name":"Australia","abbrev":"auz"},
    {"name":"Austria","abbrev":"aust"},
    {"name":"Azerbaijan","abbrev":"aze"},
    {"name":"Burundi","abbrev":"bur"},
    {"name":"Belgium","abbrev":"belg"},
    {"name":"Benin","abbrev":"benin"},
    {"name":"Burkina Faso","abbrev":"bf"},
    {"name":"Bangladesh","abbrev":"bang"},
    {"name":"Bulgaria","abbrev":"bulg"},
    {"name":"Bahrain","abbrev":"bahr"},
    {"name":"Bahamas","abbrev":"bhs"},
    {"name":"Bosnia and Herz.","abbrev":"bh"},
    {"name":"Bajo Nuevo Bank (Petrel Is.)","abbrev":"bjn"},
    {"name":"Belarus","abbrev":"bela"},
    {"name":"Belize","abbrev":"belize"},
    {"name":"Bolivia","abbrev":"bolivia"},
    {"name":"Brazil","abbrev":"brazil"},
    {"name":"Barbados","abbrev":"barb"},
    {"name":"Brunei","abbrev":"brunei"},
    {"name":"Bhutan","abbrev":"bhutan"},
    {"name":"Botswana","abbrev":"bwa"},
    {"name":"Central African Rep.","abbrev":"car"},
    {"name":"Canada","abbrev":"can"},
    {"name":"China","abbrev":"china"},
    {"name":"Switzerland","abbrev":"switz"},
    {"name":"Chile","abbrev":"chile"},
    {"name":"Côte d'Ivoire","abbrev":"ic"},
    {"name":"Cameroon","abbrev":"cam"},
    {"name":"Cyprus U.N. Buffer Zone","abbrev":"cnm"},
    {"name":"Democratic Republic of the Congo","abbrev":"drc"},
    {"name":"Republic of Congo","abbrev":"repcongo"},
    {"name":"Colombia","abbrev":"col"},
    {"name":"Comoros","abbrev":"com"},
    {"name":"Cape Verde","abbrev":"cvd"},
    {"name":"Costa Rica","abbrev":"cr"},
    {"name":"Cuba","abbrev":"cuba"},
    {"name":"N. Cyprus","abbrev":"ncy"},
    {"name":"Cyprus","abbrev":"cyp"},
    {"name":"Czech Rep.","abbrev":"czrep"},
    {"name":"Germany","abbrev":"ger"},
    {"name":"Djibouti","abbrev":"dji"},
    {"name":"Dominica","abbrev":"dinca"},
    {"name":"Denmark","abbrev":"den"},
    {"name":"Dominican Rep.","abbrev":"domrep"},
    {"name":"Algeria","abbrev":"alg"},
    {"name":"Ecuador","abbrev":"ecu"},
    {"name":"Egypt","abbrev":"egypt"},
    {"name":"Eritrea","abbrev":"erit"},
    {"name":"Spain","abbrev":"sp"},
    {"name":"Estonia","abbrev":"est"},
    {"name":"Ethiopia","abbrev":"eth"},
    {"name":"Finland","abbrev":"fin"},
    {"name":"Fiji","abbrev":"fiji"},
    {"name":"France","abbrev":"fr"},
    {"name":"Micronesia","abbrev":"fsm"},
    {"name":"Gabon","abbrev":"gabon"},
    {"name":"United Kingdom","abbrev":"uk"},
    {"name":"Georgia","abbrev":"geo"},
    {"name":"Ghana","abbrev":"ghana"},
    {"name":"Guinea","abbrev":"gin"},
    {"name":"Gambia","abbrev":"gambia"},
    {"name":"Guinea-Bissau","abbrev":"gnb"},
    {"name":"Eq. Guinea","abbrev":"eqg"},
    {"name":"Greece","abbrev":"greece"},
    {"name":"Grenada","abbrev":"gren"},
    {"name":"Guatemala","abbrev":"guat"},
    {"name":"Guyana","abbrev":"guy"},
    {"name":"Honduras","abbrev":"hond"},
    {"name":"Croatia","abbrev":"cro"},
    {"name":"Haiti","abbrev":"haiti"},
    {"name":"Hungary","abbrev":"hun"},
    {"name":"Indonesia","abbrev":"indo"},
    {"name":"India","abbrev":"india"},
    {"name":"Ireland","abbrev":"ire"},
    {"name":"Iran","abbrev":"iran"},
    {"name":"Iraq","abbrev":"iraq"},
    {"name":"Israel","abbrev":"isr"},
    {"name":"Iceland","abbrev":"iceland"},
    {"name":"Italy","abbrev":"italy"},
    {"name":"Jamaica","abbrev":"jam"},
    {"name":"Jordan","abbrev":"jord"},
    {"name":"Japan","abbrev":"japan"},
    {"name":"Siachen Glacier","abbrev":"siachen"},
    {"name":"Kazakhstan","abbrev":"kaz"},
    {"name":"Kenya","abbrev":"ken"},
    {"name":"Kyrgyzstan","abbrev":"kgz"},
    {"name":"Cambodia","abbrev":"camb"},
    {"name":"Kiribati","abbrev":"kir"},
    {"name":"Saint Kitts and Nevis","abbrev":"stkn"},
    {"name":"Republic of Korea","abbrev":"sk"},
    {"name":"Kosovo","abbrev":"kos"},
    {"name":"Kuwait","abbrev":"kwt"},
    {"name":"Laos","abbrev":"laos"},
    {"name":"Lebanon","abbrev":"leb"},
    {"name":"Liberia","abbrev":"liberia"},
    {"name":"Libya","abbrev":"libya"},
    {"name":"Saint Lucia","abbrev":"sl"},
    {"name":"Liechtenstein","abbrev":"liech"},
    {"name":"Sri Lanka","abbrev":"sril"},
    {"name":"Lesotho","abbrev":"les"},
    {"name":"Lithuania","abbrev":"lith"},
    {"name":"Luxembourg","abbrev":"lux"},
    {"name":"Latvia","abbrev":"lat"},
    {"name":"Morocco","abbrev":"mor"},
    {"name":"Monaco","abbrev":"mco"},
    {"name":"Moldova","abbrev":"mda"},
    {"name":"Madagascar","abbrev":"mad"},
    {"name":"Maldives","abbrev":"mald"},
    {"name":"Mexico","abbrev":"mex"},
    {"name":"Marshall Is.","abbrev":"mis"},
    {"name":"Macedonia","abbrev":"mkd"},
    {"name":"Mali","abbrev":"mali"},
    {"name":"Malta","abbrev":"malta"},
    {"name":"Myanmar","abbrev":"myan"},
    {"name":"Montenegro","abbrev":"mont"},
    {"name":"Mongolia","abbrev":"mong"},
    {"name":"Mozambique","abbrev":"moz"},
    {"name":"Mauritania","abbrev":"mrt"},
    {"name":"Mauritius","abbrev":"mus"},
    {"name":"Malawi","abbrev":"mal"},
    {"name":"Malaysia","abbrev":"malay"},
    {"name":"Namibia","abbrev":"nam"},
    {"name":"Niger","abbrev":"niger"},
    {"name":"Nigeria","abbrev":"nigeria"},
    {"name":"Nicaragua","abbrev":"nic"},
    {"name":"Netherlands","abbrev":"neth"},
    {"name":"Norway","abbrev":"nor"},
    {"name":"Nepal","abbrev":"nepal"},
    {"name":"Nauru","abbrev":"nauru"},
    {"name":"New Zealand","abbrev":"nz"},
    {"name":"Oman","abbrev":"oman"},
    {"name":"Pakistan","abbrev":"pak"},
    {"name":"Panama","abbrev":"pan"},
    {"name":"Peru","abbrev":"peru"},
    {"name":"Spratly Is.","abbrev":"spratlyis"},
    {"name":"Philippines","abbrev":"phil"},
    {"name":"Palau","abbrev":"palau"},
    {"name":"Papua New Guinea","abbrev":"png"},
    {"name":"Poland","abbrev":"pol"},
    {"name":"Dem. Rep. Korea","abbrev":"nk"},
    {"name":"Portugal","abbrev":"port"},
    {"name":"Paraguay","abbrev":"para"},
    {"name":"Qatar","abbrev":"qatar"},
    {"name":"Romania","abbrev":"rom"},
    {"name":"Russia","abbrev":"rus"},
    {"name":"Rwanda","abbrev":"rwa"},
    {"name":"W. Sahara","abbrev":"wsah"},
    {"name":"Saudi Arabia","abbrev":"saud"},
    {"name":"Scarborough Reef","abbrev":"sr"},
    {"name":"Sudan","abbrev":"sudan"},
    {"name":"S. Sudan","abbrev":"ssud"},
    {"name":"Senegal","abbrev":"sen"},
    {"name":"Serranilla Bank","abbrev":"sb"},
    {"name":"Singapore","abbrev":"sing"},
    {"name":"Solomon Is.","abbrev":"sis"},
    {"name":"Sierra Leone","abbrev":"sl"},
    {"name":"El Salvador","abbrev":"els"},
    {"name":"San Marino","abbrev":"sm"},
    {"name":"Somaliland","abbrev":"solnd"},
    {"name":"Somalia","abbrev":"som"},
    {"name":"Serbia","abbrev":"serb"},
    {"name":"Sao Tome and Principe","abbrev":"stp"},
    {"name":"Suriname","abbrev":"sur"},
    {"name":"Slovakia","abbrev":"svk"},
    {"name":"Slovenia","abbrev":"slo"},
    {"name":"Sweden","abbrev":"swe"},
    {"name":"Swaziland","abbrev":"swz"},
    {"name":"Seychelles","abbrev":"syc"},
    {"name":"Syria","abbrev":"syria"},
    {"name":"Chad","abbrev":"chad"},
    {"name":"Togo","abbrev":"togo"},
    {"name":"Thailand","abbrev":"thai"},
    {"name":"Tajikistan","abbrev":"tjk"},
    {"name":"Turkmenistan","abbrev":"turkm"},
    {"name":"Timor-Leste","abbrev":"tl"},
    {"name":"Tonga","abbrev":"tongo"},
    {"name":"Trinidad and Tobago","abbrev":"trt"},
    {"name":"Tunisia","abbrev":"tun"},
    {"name":"Turkey","abbrev":"tur"},
    {"name":"Tuvalu","abbrev":"tuv"},
    {"name":"Taiwan","abbrev":"taiwan"},
    {"name":"Tanzania","abbrev":"tanz"},
    {"name":"Uganda","abbrev":"uga"},
    {"name":"Ukraine","abbrev":"ukr"},
    {"name":"Uruguay","abbrev":"ury"},
    {"name":"United States","abbrev":"usa"},
    {"name":"Uzbekistan","abbrev":"uzb"},
    {"name":"Vatican","abbrev":"vat"},
    {"name":"St. Vin. and Gren.","abbrev":"stvg"},
    {"name":"Venezuela","abbrev":"ven"},
    {"name":"Vietnam","abbrev":"viet"},
    {"name":"Vanuatu","abbrev":"van"},
    {"name":"Samoa","abbrev":"samoa"},
    {"name":"Yemen","abbrev":"yem"},
    {"name":"South Africa","abbrev":"saf"},
    {"name":"Zambia","abbrev":"zambia"},
    {"name":"Zimbabwe","abbrev":"zimb"}
  ],
    "cities":[
    {"usa": [
      {"name":"San Fernando city","abbrev":"sanfernandocity"},
      {"name":"Cloverdale city","abbrev":"cloverdalecity"},
      {"name":"Cotati city","abbrev":"cotaticity"},
      {"name":"San Buenaventura (Ventura) city","abbrev":"sanbuenaventuraventuracity"},
      {"name":"Glendora city","abbrev":"glendoracity"},
      {"name":"Hawthorne city","abbrev":"hawthornecity"},
      {"name":"Inglewood city","abbrev":"inglewoodcity"},
      {"name":"La Caada Flintridge city","abbrev":"lacaadaflintridgecity"},
      {"name":"La Mirada city","abbrev":"lamiradacity"},
      {"name":"Palmdale city","abbrev":"palmdalecity"},
      {"name":"Palos Verdes Estates city","abbrev":"palosverdesestatescity"},
      {"name":"Rolling Hills city","abbrev":"rollinghillscity"},
      {"name":"Santa Clarita city","abbrev":"santaclaritacity"},
      {"name":"Santa Fe Springs city","abbrev":"santafespringscity"},
      {"name":"Vernon city","abbrev":"vernoncity"},
      {"name":"Walnut city","abbrev":"walnutcity"},
      {"name":"Sierra Madre city","abbrev":"sierramadrecity"},
      {"name":"South Pasadena city","abbrev":"southpasadenacity"},
      {"name":"Calabasas city","abbrev":"calabasascity"},
      {"name":"Rolling Hills Estates city","abbrev":"rollinghillsestatescity"},
      {"name":"Benicia city","abbrev":"beniciacity"},
      {"name":"Dixon city","abbrev":"dixoncity"},
      {"name":"Rio Vista city","abbrev":"riovistacity"},
      {"name":"Lynwood city","abbrev":"lynwoodcity"},
      {"name":"Suisun City city","abbrev":"suisuncitycity"},
      {"name":"Moorpark city","abbrev":"moorparkcity"},
      {"name":"Rohnert Park city","abbrev":"rohnertparkcity"},
      {"name":"Sebastopol city","abbrev":"sebastopolcity"},
      {"name":"Sonoma city","abbrev":"sonomacity"},
      {"name":"Camarillo city","abbrev":"camarillocity"},
      {"name":"Fillmore city","abbrev":"fillmorecity"},
      {"name":"Oxnard city","abbrev":"oxnardcity"},
      {"name":"Los Gatos town","abbrev":"losgatostown"},
      {"name":"Gilroy city","abbrev":"gilroycity"},
      {"name":"Saratoga city","abbrev":"saratogacity"},
      {"name":"Dunsmuir city","abbrev":"dunsmuircity"},
      {"name":"Etna city","abbrev":"etnacity"},
      {"name":"Fort Jones city","abbrev":"fortjonescity"},
      {"name":"Montague city","abbrev":"montaguecity"},
      {"name":"Weed city","abbrev":"weedcity"},
      {"name":"Baldwin Park city","abbrev":"baldwinparkcity"},
      {"name":"Beverly Hills city","abbrev":"beverlyhillscity"},
      {"name":"Glendale city","abbrev":"glendalecity"},
      {"name":"La Puente city","abbrev":"lapuentecity"},
      {"name":"Los Angeles city","abbrev":"losangelescity"},
      {"name":"Paramount city","abbrev":"paramountcity"},
      {"name":"Temple City city","abbrev":"templecitycity"},
      {"name":"Rancho Cucamonga city","abbrev":"ranchocucamongacity"},
      {"name":"Campbell city","abbrev":"campbellcity"},
      {"name":"Cupertino city","abbrev":"cupertinocity"},
      {"name":"Los Altos Hills town","abbrev":"losaltoshillstown"},
      {"name":"Monte Sereno city","abbrev":"monteserenocity"},
      {"name":"Palo Alto city","abbrev":"paloaltocity"},
      {"name":"San Jose city","abbrev":"sanjosecity"},
      {"name":"Port Hueneme city","abbrev":"porthuenemecity"},
      {"name":"Marysville city","abbrev":"marysvillecity"},
      {"name":"Barstow city","abbrev":"barstowcity"},
      {"name":"Colton city","abbrev":"coltoncity"},
      {"name":"Grand Terrace city","abbrev":"grandterracecity"},
      {"name":"Tulelake city","abbrev":"tulelakecity"},
      {"name":"Lincoln city","abbrev":"lincolncity"},
      {"name":"Loomis town","abbrev":"loomistown"},
      {"name":"San Bruno city","abbrev":"sanbrunocity"},
      {"name":"Point Arena city","abbrev":"pointarenacity"},
      {"name":"Willits city","abbrev":"willitscity"},
      {"name":"Corte Madera town","abbrev":"cortemaderatown"},
      {"name":"Ross town","abbrev":"rosstown"},
      {"name":"San Anselmo town","abbrev":"sananselmotown"},
      {"name":"Mill Valley city","abbrev":"millvalleycity"},
      {"name":"Tiburon town","abbrev":"tiburontown"},
      {"name":"Atherton town","abbrev":"athertontown"},
      {"name":"Brisbane city","abbrev":"brisbanecity"},
      {"name":"Colma town","abbrev":"colmatown"},
      {"name":"East Palo Alto city","abbrev":"eastpaloaltocity"},
      {"name":"Foster City city","abbrev":"fostercitycity"},
      {"name":"Half Moon Bay city","abbrev":"halfmoonbaycity"},
      {"name":"Hillsborough town","abbrev":"hillsboroughtown"},
      {"name":"Millbrae city","abbrev":"millbraecity"},
      {"name":"Pacifica city","abbrev":"pacificacity"},
      {"name":"Belvedere city","abbrev":"belvederecity"},
      {"name":"Ceres city","abbrev":"cerescity"},
      {"name":"Hughson city","abbrev":"hughsoncity"},
      {"name":"Newman city","abbrev":"newmancity"},
      {"name":"Live Oak city","abbrev":"liveoakcity"},
      {"name":"San Francisco city","abbrev":"sanfranciscocity"},
      {"name":"Oakdale city","abbrev":"oakdalecity"},
      {"name":"Dos Palos city","abbrev":"dospaloscity"},
      {"name":"Gustine city","abbrev":"gustinecity"},
      {"name":"Pacific Grove city","abbrev":"pacificgrovecity"},
      {"name":"Livingston city","abbrev":"livingstoncity"},
      {"name":"Portola city","abbrev":"portolacity"},
      {"name":"San Juan Bautista city","abbrev":"sanjuanbautistacity"},
      {"name":"Menlo Park city","abbrev":"menloparkcity"},
      {"name":"San Mateo city","abbrev":"sanmateocity"},
      {"name":"Portola Valley town","abbrev":"portolavalleytown"},
      {"name":"Lawndale city","abbrev":"lawndalecity"},
      {"name":"Corning city","abbrev":"corningcity"},
      {"name":"Tehama city","abbrev":"tehamacity"},
      {"name":"Vallejo city","abbrev":"vallejocity"},
      {"name":"Riverside city","abbrev":"riversidecity"},
      {"name":"Moreno Valley city","abbrev":"morenovalleycity"},
      {"name":"Corona city","abbrev":"coronacity"},
      {"name":"Lake Elsinore city","abbrev":"lakeelsinorecity"},
      {"name":"Beaumont city","abbrev":"beaumontcity"},
      {"name":"Hemet city","abbrev":"hemetcity"},
      {"name":"Norco city","abbrev":"norcocity"},
      {"name":"Cathedral City city","abbrev":"cathedralcitycity"},
      {"name":"San Jacinto city","abbrev":"sanjacintocity"},
      {"name":"Palm Desert city","abbrev":"palmdesertcity"},
      {"name":"La Habra Heights city","abbrev":"lahabraheightscity"},
      {"name":"Sunnyvale city","abbrev":"sunnyvalecity"},
      {"name":"Mountain View city","abbrev":"mountainviewcity"},
      {"name":"Los Altos city","abbrev":"losaltoscity"},
      {"name":"Santa Clara city","abbrev":"santaclaracity"},
      {"name":"Morgan Hill city","abbrev":"morganhillcity"},
      {"name":"Pomona city","abbrev":"pomonacity"},
      {"name":"Industry city","abbrev":"industrycity"},
      {"name":"Diamond Bar city","abbrev":"diamondbarcity"},
      {"name":"Duarte city","abbrev":"duartecity"},
      {"name":"Arcadia city","abbrev":"arcadiacity"},
      {"name":"South El Monte city","abbrev":"southelmontecity"},
      {"name":"Monterey Park city","abbrev":"montereyparkcity"},
      {"name":"West Hollywood city","abbrev":"westhollywoodcity"},
      {"name":"West Covina city","abbrev":"westcovinacity"},
      {"name":"La Verne city","abbrev":"lavernecity"},
      {"name":"Irwindale city","abbrev":"irwindalecity"},
      {"name":"San Marino city","abbrev":"sanmarinocity"},
      {"name":"Burbank city","abbrev":"burbankcity"},
      {"name":"Azusa city","abbrev":"azusacity"},
      {"name":"Westlake Village city","abbrev":"westlakevillagecity"},
      {"name":"Turlock city","abbrev":"turlockcity"},
      {"name":"Fairfax town","abbrev":"fairfaxtown"},
      {"name":"Larkspur city","abbrev":"larkspurcity"},
      {"name":"Novato city","abbrev":"novatocity"},
      {"name":"Long Beach city","abbrev":"longbeachcity"},
      {"name":"Signal Hill city","abbrev":"signalhillcity"},
      {"name":"Rancho Palos Verdes city","abbrev":"ranchopalosverdescity"},
      {"name":"Malibu city","abbrev":"malibucity"},
      {"name":"Lancaster city","abbrev":"lancastercity"},
      {"name":"Alhambra city","abbrev":"alhambracity"},
      {"name":"Rosemead city","abbrev":"rosemeadcity"},
      {"name":"Montebello city","abbrev":"montebellocity"},
      {"name":"Gardena city","abbrev":"gardenacity"},
      {"name":"Lakewood city","abbrev":"lakewoodcity"},
      {"name":"Compton city","abbrev":"comptoncity"},
      {"name":"San Gabriel city","abbrev":"sangabrielcity"},
      {"name":"Norwalk city","abbrev":"norwalkcity"},
      {"name":"Downey city","abbrev":"downeycity"},
      {"name":"Whittier city","abbrev":"whittiercity"},
      {"name":"Pico Rivera city","abbrev":"picoriveracity"},
      {"name":"Bell city","abbrev":"bellcity"},
      {"name":"Huntington Park city","abbrev":"huntingtonparkcity"},
      {"name":"South Gate city","abbrev":"southgatecity"},
      {"name":"Culver City city","abbrev":"culvercitycity"},
      {"name":"Chico city","abbrev":"chicocity"},
      {"name":"Oroville city","abbrev":"orovillecity"},
      {"name":"Capitola city","abbrev":"capitolacity"},
      {"name":"Scotts Valley city","abbrev":"scottsvalleycity"},
      {"name":"Crescent City city","abbrev":"crescentcitycity"},
      {"name":"Madera city","abbrev":"maderacity"},
      {"name":"Patterson city","abbrev":"pattersoncity"},
      {"name":"Riverbank city","abbrev":"riverbankcity"},
      {"name":"Waterford city","abbrev":"waterfordcity"},
      {"name":"Modesto city","abbrev":"modestocity"},
      {"name":"Hayward city","abbrev":"haywardcity"},
      {"name":"Livermore city","abbrev":"livermorecity"},
      {"name":"Pleasanton city","abbrev":"pleasantoncity"},
      {"name":"Wheatland city","abbrev":"wheatlandcity"},
      {"name":"Blue Lake city","abbrev":"bluelakecity"},
      {"name":"Fortuna city","abbrev":"fortunacity"},
      {"name":"Rio Dell city","abbrev":"riodellcity"},
      {"name":"Trinidad city","abbrev":"trinidadcity"},
      {"name":"Ferndale city","abbrev":"ferndalecity"},
      {"name":"Arcata city","abbrev":"arcatacity"},
      {"name":"Eureka city","abbrev":"eurekacity"},
      {"name":"Redondo Beach city","abbrev":"redondobeachcity"},
      {"name":"Torrance city","abbrev":"torrancecity"},
      {"name":"Visalia city","abbrev":"visaliacity"},
      {"name":"Menifee city","abbrev":"menifeecity"},
      {"name":"Belmont city","abbrev":"belmontcity"},
      {"name":"Burlingame city","abbrev":"burlingamecity"},
      {"name":"Daly City city","abbrev":"dalycitycity"},
      {"name":"San Carlos city","abbrev":"sancarloscity"},
      {"name":"South San Francisco city","abbrev":"southsanfranciscocity"},
      {"name":"Woodside town","abbrev":"woodsidetown"},
      {"name":"Wildomar city","abbrev":"wildomarcity"},
      {"name":"Banning city","abbrev":"banningcity"},
      {"name":"Brea city","abbrev":"breacity"},
      {"name":"Irvine city","abbrev":"irvinecity"},
      {"name":"La Habra city","abbrev":"lahabracity"},
      {"name":"Stanton city","abbrev":"stantoncity"},
      {"name":"Ojai city","abbrev":"ojaicity"},
      {"name":"Simi Valley city","abbrev":"simivalleycity"},
      {"name":"Thousand Oaks city","abbrev":"thousandoakscity"},
      {"name":"Rocklin city","abbrev":"rocklincity"},
      {"name":"Auburn city","abbrev":"auburncity"},
      {"name":"Roseville city","abbrev":"rosevillecity"},
      {"name":"Sonora city","abbrev":"sonoracity"},
      {"name":"Piedmont city","abbrev":"piedmontcity"},
      {"name":"Los Banos city","abbrev":"losbanoscity"},
      {"name":"Chowchilla city","abbrev":"chowchillacity"},
      {"name":"Calimesa city","abbrev":"calimesacity"},
      {"name":"Canyon Lake city","abbrev":"canyonlakecity"},
      {"name":"Coachella city","abbrev":"coachellacity"},
      {"name":"Indian Wells city","abbrev":"indianwellscity"},
      {"name":"La Quinta city","abbrev":"laquintacity"},
      {"name":"Nevada City city","abbrev":"nevadacitycity"},
      {"name":"Truckee town","abbrev":"truckeetown"},
      {"name":"Porterville city","abbrev":"portervillecity"},
      {"name":"Tulare city","abbrev":"tularecity"},
      {"name":"Atwater city","abbrev":"atwatercity"},
      {"name":"Merced city","abbrev":"mercedcity"},
      {"name":"Rancho Mirage city","abbrev":"ranchomiragecity"},
      {"name":"Temecula city","abbrev":"temeculacity"},
      {"name":"Desert Hot Springs city","abbrev":"deserthotspringscity"},
      {"name":"Palm Springs city","abbrev":"palmspringscity"},
      {"name":"Placerville city","abbrev":"placervillecity"},
      {"name":"Petaluma city","abbrev":"petalumacity"},
      {"name":"Santa Rosa city","abbrev":"santarosacity"},
      {"name":"Orland city","abbrev":"orlandcity"},
      {"name":"Willows city","abbrev":"willowscity"},
      {"name":"San Joaquin city","abbrev":"sanjoaquincity"},
      {"name":"La Palma city","abbrev":"lapalmacity"},
      {"name":"Los Alamitos city","abbrev":"losalamitoscity"},
      {"name":"Mission Viejo city","abbrev":"missionviejocity"},
      {"name":"Rancho Santa Margarita city","abbrev":"ranchosantamargaritacity"},
      {"name":"Avenal city","abbrev":"avenalcity"},
      {"name":"San Clemente city","abbrev":"sanclementecity"},
      {"name":"Seal Beach city","abbrev":"sealbeachcity"},
      {"name":"Villa Park city","abbrev":"villaparkcity"},
      {"name":"Aliso Viejo city","abbrev":"alisoviejocity"},
      {"name":"Huntington Beach city","abbrev":"huntingtonbeachcity"},
      {"name":"Tustin city","abbrev":"tustincity"},
      {"name":"Buena Park city","abbrev":"buenaparkcity"},
      {"name":"Dana Point city","abbrev":"danapointcity"},
      {"name":"Lemoore city","abbrev":"lemoorecity"},
      {"name":"Fountain Valley city","abbrev":"fountainvalleycity"},
      {"name":"Laguna Beach city","abbrev":"lagunabeachcity"},
      {"name":"Laguna Hills city","abbrev":"lagunahillscity"},
      {"name":"Laguna Woods city","abbrev":"lagunawoodscity"},
      {"name":"Lake Forest city","abbrev":"lakeforestcity"},
      {"name":"Hanford city","abbrev":"hanfordcity"},
      {"name":"Clayton city","abbrev":"claytoncity"},
      {"name":"El Cerrito city","abbrev":"elcerritocity"},
      {"name":"Hercules city","abbrev":"herculescity"},
      {"name":"Moraga town","abbrev":"moragatown"},
      {"name":"Lathrop city","abbrev":"lathropcity"},
      {"name":"Lodi city","abbrev":"lodicity"},
      {"name":"Manteca city","abbrev":"mantecacity"},
      {"name":"Tracy city","abbrev":"tracycity"},
      {"name":"Jurupa Valley city","abbrev":"jurupavalleycity"},
      {"name":"Calipatria city","abbrev":"calipatriacity"},
      {"name":"Susanville city","abbrev":"susanvillecity"},
      {"name":"Anaheim city","abbrev":"anaheimcity"},
      {"name":"Costa Mesa city","abbrev":"costamesacity"},
      {"name":"Cypress city","abbrev":"cypresscity"},
      {"name":"Fullerton city","abbrev":"fullertoncity"},
      {"name":"Garden Grove city","abbrev":"gardengrovecity"},
      {"name":"Laguna Niguel city","abbrev":"lagunaniguelcity"},
      {"name":"Orange city","abbrev":"orangecity"},
      {"name":"Placentia city","abbrev":"placentiacity"},
      {"name":"San Juan Capistrano city","abbrev":"sanjuancapistranocity"},
      {"name":"Santa Ana city","abbrev":"santaanacity"},
      {"name":"Westminster city","abbrev":"westminstercity"},
      {"name":"Yorba Linda city","abbrev":"yorbalindacity"},
      {"name":"Williams city","abbrev":"williamscity"},
      {"name":"Colusa city","abbrev":"colusacity"},
      {"name":"Escalon city","abbrev":"escaloncity"},
      {"name":"Ripon city","abbrev":"riponcity"},
      {"name":"Stockton city","abbrev":"stocktoncity"},
      {"name":"Apple Valley town","abbrev":"applevalleytown"},
      {"name":"San Bernardino city","abbrev":"sanbernardinocity"},
      {"name":"Hesperia city","abbrev":"hesperiacity"},
      {"name":"Santa Paula city","abbrev":"santapaulacity"},
      {"name":"Redding city","abbrev":"reddingcity"},
      {"name":"Shasta Lake city","abbrev":"shastalakecity"},
      {"name":"Victorville city","abbrev":"victorvillecity"},
      {"name":"Chino Hills city","abbrev":"chinohillscity"},
      {"name":"Highland city","abbrev":"highlandcity"},
      {"name":"Chino city","abbrev":"chinocity"},
      {"name":"Bakersfield city","abbrev":"bakersfieldcity"},
      {"name":"Blythe city","abbrev":"blythecity"},
      {"name":"Indio city","abbrev":"indiocity"},
      {"name":"Perris city","abbrev":"perriscity"},
      {"name":"Arvin city","abbrev":"arvincity"},
      {"name":"Ridgecrest city","abbrev":"ridgecrestcity"},
      {"name":"Tehachapi city","abbrev":"tehachapicity"},
      {"name":"Brentwood city","abbrev":"brentwoodcity"},
      {"name":"Redwood City city","abbrev":"redwoodcitycity"},
      {"name":"San Rafael city","abbrev":"sanrafaelcity"},
      {"name":"Carmel-by-the-Sea city","abbrev":"carmel-by-the-seacity"},
      {"name":"Del Rey Oaks city","abbrev":"delreyoakscity"},
      {"name":"Huron city","abbrev":"huroncity"},
      {"name":"Gonzales city","abbrev":"gonzalescity"},
      {"name":"Greenfield city","abbrev":"greenfieldcity"},
      {"name":"Red Bluff city","abbrev":"redbluffcity"},
      {"name":"Davis city","abbrev":"daviscity"},
      {"name":"West Sacramento city","abbrev":"westsacramentocity"},
      {"name":"Winters city","abbrev":"winterscity"},
      {"name":"Woodland city","abbrev":"woodlandcity"},
      {"name":"Fairfield city","abbrev":"fairfieldcity"},
      {"name":"Vacaville city","abbrev":"vacavillecity"},
      {"name":"Dorris city","abbrev":"dorriscity"},
      {"name":"Mount Shasta city","abbrev":"mountshastacity"},
      {"name":"Ukiah city","abbrev":"ukiahcity"},
      {"name":"Lakeport city","abbrev":"lakeportcity"},
      {"name":"Coronado city","abbrev":"coronadocity"},
      {"name":"Escondido city","abbrev":"escondidocity"},
      {"name":"Imperial Beach city","abbrev":"imperialbeachcity"},
      {"name":"Delano city","abbrev":"delanocity"},
      {"name":"McFarland city","abbrev":"mcfarlandcity"},
      {"name":"Maricopa city","abbrev":"maricopacity"},
      {"name":"Marina city","abbrev":"marinacity"},
      {"name":"Sand City city","abbrev":"sandcitycity"},
      {"name":"Seaside city","abbrev":"seasidecity"},
      {"name":"Soledad city","abbrev":"soledadcity"},
      {"name":"Colfax city","abbrev":"colfaxcity"},
      {"name":"Anderson city","abbrev":"andersoncity"},
      {"name":"Yreka city","abbrev":"yrekacity"},
      {"name":"Mammoth Lakes town","abbrev":"mammothlakestown"},
      {"name":"Oakland city","abbrev":"oaklandcity"},
      {"name":"Carson city","abbrev":"carsoncity"},
      {"name":"Lemon Grove city","abbrev":"lemongrovecity"},
      {"name":"Chula Vista city","abbrev":"chulavistacity"},
      {"name":"San Diego city","abbrev":"sandiegocity"},
      {"name":"Shafter city","abbrev":"shaftercity"},
      {"name":"Wasco city","abbrev":"wascocity"},
      {"name":"Sausalito city","abbrev":"sausalitocity"},
      {"name":"Orinda city","abbrev":"orindacity"},
      {"name":"Pinole city","abbrev":"pinolecity"},
      {"name":"Richmond city","abbrev":"richmondcity"},
      {"name":"San Pablo city","abbrev":"sanpablocity"},
      {"name":"Lafayette city","abbrev":"lafayettecity"},
      {"name":"Loma Linda city","abbrev":"lomalindacity"},
      {"name":"Montclair city","abbrev":"montclaircity"},
      {"name":"Needles city","abbrev":"needlescity"},
      {"name":"Bradbury city","abbrev":"bradburycity"},
      {"name":"Ontario city","abbrev":"ontariocity"},
      {"name":"Healdsburg city","abbrev":"healdsburgcity"},
      {"name":"Windsor town","abbrev":"windsortown"},
      {"name":"Fort Bragg city","abbrev":"fortbraggcity"},
      {"name":"Kerman city","abbrev":"kermancity"},
      {"name":"Bishop city","abbrev":"bishopcity"},
      {"name":"El Cajon city","abbrev":"elcajoncity"},
      {"name":"Encinitas city","abbrev":"encinitascity"},
      {"name":"La Mesa city","abbrev":"lamesacity"},
      {"name":"Oceanside city","abbrev":"oceansidecity"},
      {"name":"Poway city","abbrev":"powaycity"},
      {"name":"San Marcos city","abbrev":"sanmarcoscity"},
      {"name":"Alameda city","abbrev":"alamedacity"},
      {"name":"Albany city","abbrev":"albanycity"},
      {"name":"Berkeley city","abbrev":"berkeleycity"},
      {"name":"Dublin city","abbrev":"dublincity"},
      {"name":"Emeryville city","abbrev":"emeryvillecity"},
      {"name":"Vista city","abbrev":"vistacity"},
      {"name":"Newark city","abbrev":"newarkcity"},
      {"name":"San Leandro city","abbrev":"sanleandrocity"},
      {"name":"Union City city","abbrev":"unioncitycity"},
      {"name":"Fremont city","abbrev":"fremontcity"},
      {"name":"Napa city","abbrev":"napacity"},
      {"name":"St. Helena city","abbrev":"sthelenacity"},
      {"name":"King City city","abbrev":"kingcitycity"},
      {"name":"Woodlake city","abbrev":"woodlakecity"},
      {"name":"Twentynine Palms city","abbrev":"twentyninepalmscity"},
      {"name":"Upland city","abbrev":"uplandcity"},
      {"name":"Yucaipa city","abbrev":"yucaipacity"},
      {"name":"Yucca Valley town","abbrev":"yuccavalleytown"},
      {"name":"Paradise town","abbrev":"paradisetown"},
      {"name":"Corcoran city","abbrev":"corcorancity"},
      {"name":"Adelanto city","abbrev":"adelantocity"},
      {"name":"Redlands city","abbrev":"redlandscity"},
      {"name":"Carlsbad city","abbrev":"carlsbadcity"},
      {"name":"National City city","abbrev":"nationalcitycity"},
      {"name":"Santee city","abbrev":"santeecity"},
      {"name":"California City city","abbrev":"californiacitycity"},
      {"name":"Taft city","abbrev":"taftcity"},
      {"name":"Eastvale city","abbrev":"eastvalecity"},
      {"name":"Big Bear Lake city","abbrev":"bigbearlakecity"},
      {"name":"Fontana city","abbrev":"fontanacity"},
      {"name":"Rialto city","abbrev":"rialtocity"},
      {"name":"Solana Beach city","abbrev":"solanabeachcity"},
      {"name":"Murrieta city","abbrev":"murrietacity"},
      {"name":"Sutter Creek city","abbrev":"suttercreekcity"},
      {"name":"Atascadero city","abbrev":"atascaderocity"},
      {"name":"Grover Beach city","abbrev":"groverbeachcity"},
      {"name":"Pismo Beach city","abbrev":"pismobeachcity"},
      {"name":"Arroyo Grande city","abbrev":"arroyograndecity"},
      {"name":"South Lake Tahoe city","abbrev":"southlaketahoecity"},
      {"name":"Clovis city","abbrev":"cloviscity"},
      {"name":"Fresno city","abbrev":"fresnocity"},
      {"name":"Clearlake city","abbrev":"clearlakecity"},
      {"name":"Angels city","abbrev":"angelscity"},
      {"name":"Alturas city","abbrev":"alturascity"},
      {"name":"Yuba City city","abbrev":"yubacitycity"},
      {"name":"Folsom city","abbrev":"folsomcity"},
      {"name":"Isleton city","abbrev":"isletoncity"},
      {"name":"Rancho Cordova city","abbrev":"ranchocordovacity"},
      {"name":"Monterey city","abbrev":"montereycity"},
      {"name":"American Canyon city","abbrev":"americancanyoncity"},
      {"name":"Calistoga city","abbrev":"calistogacity"},
      {"name":"Yountville city","abbrev":"yountvillecity"},
      {"name":"Buellton city","abbrev":"buelltoncity"},
      {"name":"Antioch city","abbrev":"antiochcity"},
      {"name":"Concord city","abbrev":"concordcity"},
      {"name":"Danville town","abbrev":"danvilletown"},
      {"name":"Martinez city","abbrev":"martinezcity"},
      {"name":"Pittsburg city","abbrev":"pittsburgcity"},
      {"name":"Pleasant Hill city","abbrev":"pleasanthillcity"},
      {"name":"San Ramon city","abbrev":"sanramoncity"},
      {"name":"Walnut Creek city","abbrev":"walnutcreekcity"},
      {"name":"Carpinteria city","abbrev":"carpinteriacity"},
      {"name":"Guadalupe city","abbrev":"guadalupecity"},
      {"name":"Dinuba city","abbrev":"dinubacity"},
      {"name":"Exeter city","abbrev":"exetercity"},
      {"name":"Farmersville city","abbrev":"farmersvillecity"},
      {"name":"Lindsay city","abbrev":"lindsaycity"},
      {"name":"Salinas city","abbrev":"salinascity"},
      {"name":"Agoura Hills city","abbrev":"agourahillscity"},
      {"name":"Artesia city","abbrev":"artesiacity"},
      {"name":"Milpitas city","abbrev":"milpitascity"},
      {"name":"Del Mar city","abbrev":"delmarcity"},
      {"name":"Biggs city","abbrev":"biggscity"},
      {"name":"Gridley city","abbrev":"gridleycity"},
      {"name":"Avalon city","abbrev":"avaloncity"},
      {"name":"Bellflower city","abbrev":"bellflowercity"},
      {"name":"Bell Gardens city","abbrev":"bellgardenscity"},
      {"name":"Claremont city","abbrev":"claremontcity"},
      {"name":"Commerce city","abbrev":"commercecity"},
      {"name":"Cudahy city","abbrev":"cudahycity"},
      {"name":"El Monte city","abbrev":"elmontecity"},
      {"name":"Solvang city","abbrev":"solvangcity"},
      {"name":"Goleta city","abbrev":"goletacity"},
      {"name":"Lompoc city","abbrev":"lompoccity"},
      {"name":"Santa Barbara city","abbrev":"santabarbaracity"},
      {"name":"Santa Maria city","abbrev":"santamariacity"},
      {"name":"Loyalton city","abbrev":"loyaltoncity"},
      {"name":"Brawley city","abbrev":"brawleycity"},
      {"name":"El Segundo city","abbrev":"elsegundocity"},
      {"name":"Hawaiian Gardens city","abbrev":"hawaiiangardenscity"},
      {"name":"Hermosa Beach city","abbrev":"hermosabeachcity"},
      {"name":"Hidden Hills city","abbrev":"hiddenhillscity"},
      {"name":"Grass Valley city","abbrev":"grassvalleycity"},
      {"name":"Pasadena city","abbrev":"pasadenacity"},
      {"name":"Newport Beach city","abbrev":"newportbeachcity"},
      {"name":"Santa Monica city","abbrev":"santamonicacity"},
      {"name":"Calexico city","abbrev":"calexicocity"},
      {"name":"El Centro city","abbrev":"elcentrocity"},
      {"name":"Holtville city","abbrev":"holtvillecity"},
      {"name":"Imperial city","abbrev":"imperialcity"},
      {"name":"Westmorland city","abbrev":"westmorlandcity"},
      {"name":"Citrus Heights city","abbrev":"citrusheightscity"},
      {"name":"Elk Grove city","abbrev":"elkgrovecity"},
      {"name":"Galt city","abbrev":"galtcity"},
      {"name":"Sacramento city","abbrev":"sacramentocity"},
      {"name":"Hollister city","abbrev":"hollistercity"},
      {"name":"Cerritos city","abbrev":"cerritoscity"},
      {"name":"Covina city","abbrev":"covinacity"},
      {"name":"Lomita city","abbrev":"lomitacity"},
      {"name":"Manhattan Beach city","abbrev":"manhattanbeachcity"},
      {"name":"Maywood city","abbrev":"maywoodcity"},
      {"name":"Monrovia city","abbrev":"monroviacity"},
      {"name":"San Dimas city","abbrev":"sandimascity"},
      {"name":"El Paso de Robles (Paso Robles) city","abbrev":"elpasoderoblespasoroblescity"},
      {"name":"Morro Bay city","abbrev":"morrobaycity"},
      {"name":"San Luis Obispo city","abbrev":"sanluisobispocity"},
      {"name":"Oakley city","abbrev":"oakleycity"},
      {"name":"Coalinga city","abbrev":"coalingacity"},
      {"name":"Firebaugh city","abbrev":"firebaughcity"},
      {"name":"Fowler city","abbrev":"fowlercity"},
      {"name":"Kingsburg city","abbrev":"kingsburgcity"},
      {"name":"Amador City city","abbrev":"amadorcitycity"},
      {"name":"Ione city","abbrev":"ionecity"},
      {"name":"Jackson city","abbrev":"jacksoncity"},
      {"name":"Plymouth city","abbrev":"plymouthcity"},
      {"name":"Mendota city","abbrev":"mendotacity"},
      {"name":"Orange Cove city","abbrev":"orangecovecity"},
      {"name":"Parlier city","abbrev":"parliercity"},
      {"name":"Reedley city","abbrev":"reedleycity"},
      {"name":"Sanger city","abbrev":"sangercity"},
      {"name":"Selma city","abbrev":"selmacity"},
      {"name":"Watsonville city","abbrev":"watsonvillecity"},
      {"name":"Santa Cruz city","abbrev":"santacruzcity"},
      {"name":"Acalanes Ridge CDP","abbrev":"acalanesridgecdp"},
      {"name":"Acampo CDP","abbrev":"acampocdp"},
      {"name":"Acton CDP","abbrev":"actoncdp"},
      {"name":"Adin CDP","abbrev":"adincdp"},
      {"name":"Agua Dulce CDP","abbrev":"aguadulcecdp"},
      {"name":"Aguanga CDP","abbrev":"aguangacdp"},
      {"name":"Ahwahnee CDP","abbrev":"ahwahneecdp"},
      {"name":"Airport CDP","abbrev":"airportcdp"},
      {"name":"Alamo CDP","abbrev":"alamocdp"},
      {"name":"Albion CDP","abbrev":"albioncdp"},
      {"name":"Alderpoint CDP","abbrev":"alderpointcdp"},
      {"name":"Alhambra Valley CDP","abbrev":"alhambravalleycdp"},
      {"name":"Alleghany CDP","abbrev":"alleghanycdp"},
      {"name":"Allendale CDP","abbrev":"allendalecdp"},
      {"name":"Allensworth CDP","abbrev":"allensworthcdp"},
      {"name":"Almanor CDP","abbrev":"almanorcdp"},
      {"name":"Alondra Park CDP","abbrev":"alondraparkcdp"},
      {"name":"Alpaugh CDP","abbrev":"alpaughcdp"},
      {"name":"Alpine CDP","abbrev":"alpinecdp"},
      {"name":"Alpine Village CDP","abbrev":"alpinevillagecdp"},
      {"name":"Alta CDP","abbrev":"altacdp"},
      {"name":"Altadena CDP","abbrev":"altadenacdp"},
      {"name":"Alta Sierra CDP","abbrev":"altasierracdp"},
      {"name":"Alto CDP","abbrev":"altocdp"},
      {"name":"Alum Rock CDP","abbrev":"alumrockcdp"},
      {"name":"Amesti CDP","abbrev":"amesticdp"},
      {"name":"Anchor Bay CDP","abbrev":"anchorbaycdp"},
      {"name":"Angwin CDP","abbrev":"angwincdp"},
      {"name":"Antelope CDP","abbrev":"antelopecdp"},
      {"name":"Anza CDP","abbrev":"anzacdp"},
      {"name":"Aptos CDP","abbrev":"aptoscdp"},
      {"name":"Aptos Hills-Larkin Valley CDP","abbrev":"aptoshills-larkinvalleycdp"},
      {"name":"Arbuckle CDP","abbrev":"arbucklecdp"},
      {"name":"Arden-Arcade CDP","abbrev":"arden-arcadecdp"},
      {"name":"Armona CDP","abbrev":"armonacdp"},
      {"name":"Arnold CDP","abbrev":"arnoldcdp"},
      {"name":"Aromas CDP","abbrev":"aromascdp"},
      {"name":"Artois CDP","abbrev":"artoiscdp"},
      {"name":"Ashland CDP","abbrev":"ashlandcdp"},
      {"name":"Aspen Springs CDP","abbrev":"aspenspringscdp"},
      {"name":"Auberry CDP","abbrev":"auberrycdp"},
      {"name":"Auburn Lake Trails CDP","abbrev":"auburnlaketrailscdp"},
      {"name":"August CDP","abbrev":"augustcdp"},
      {"name":"Avery CDP","abbrev":"averycdp"},
      {"name":"Avilla Beach CDP","abbrev":"avillabeachcdp"},
      {"name":"Avocado Heights CDP","abbrev":"avocadoheightscdp"},
      {"name":"Baker CDP","abbrev":"bakercdp"},
      {"name":"Ballard CDP","abbrev":"ballardcdp"},
      {"name":"Ballico CDP","abbrev":"ballicocdp"},
      {"name":"Bangor CDP","abbrev":"bangorcdp"},
      {"name":"Bass Lake CDP","abbrev":"basslakecdp"},
      {"name":"Bay Point CDP","abbrev":"baypointcdp"},
      {"name":"Bayview CDP","abbrev":"bayviewcdp"},
      {"name":"Bayview CDP","abbrev":"bayviewcdp"},
      {"name":"Beale AFB CDP","abbrev":"bealeafbcdp"},
      {"name":"Bear Creek CDP","abbrev":"bearcreekcdp"},
      {"name":"Bear Valley CDP","abbrev":"bearvalleycdp"},
      {"name":"Bear Valley CDP","abbrev":"bearvalleycdp"},
      {"name":"Bear Valley Springs CDP","abbrev":"bearvalleyspringscdp"},
      {"name":"Beckwourth CDP","abbrev":"beckwourthcdp"},
      {"name":"Belden CDP","abbrev":"beldencdp"},
      {"name":"Bella Vista CDP","abbrev":"bellavistacdp"},
      {"name":"Bell Canyon CDP","abbrev":"bellcanyoncdp"},
      {"name":"Benbow CDP","abbrev":"benbowcdp"},
      {"name":"Bend CDP","abbrev":"bendcdp"},
      {"name":"Ben Lomond CDP","abbrev":"benlomondcdp"},
      {"name":"Benton CDP","abbrev":"bentoncdp"},
      {"name":"Bermuda Dunes CDP","abbrev":"bermudadunescdp"},
      {"name":"Berry Creek CDP","abbrev":"berrycreekcdp"},
      {"name":"Bertsch-Oceanview CDP","abbrev":"bertsch-oceanviewcdp"},
      {"name":"Bethel Island CDP","abbrev":"bethelislandcdp"},
      {"name":"Bieber CDP","abbrev":"biebercdp"},
      {"name":"Big Bear City CDP","abbrev":"bigbearcitycdp"},
      {"name":"Big Bend CDP","abbrev":"bigbendcdp"},
      {"name":"Big Creek CDP","abbrev":"bigcreekcdp"},
      {"name":"Big Lagoon CDP","abbrev":"biglagooncdp"},
      {"name":"Big Pine CDP","abbrev":"bigpinecdp"},
      {"name":"Big River CDP","abbrev":"bigrivercdp"},
      {"name":"Biola CDP","abbrev":"biolacdp"},
      {"name":"Blackhawk CDP","abbrev":"blackhawkcdp"},
      {"name":"Blacklake CDP","abbrev":"blacklakecdp"},
      {"name":"Black Point-Green Point CDP","abbrev":"blackpoint-greenpointcdp"},
      {"name":"Blairsden CDP","abbrev":"blairsdencdp"},
      {"name":"Bloomfield CDP","abbrev":"bloomfieldcdp"},
      {"name":"Bloomington CDP","abbrev":"bloomingtoncdp"},
      {"name":"Bluewater CDP","abbrev":"bluewatercdp"},
      {"name":"Bodega CDP","abbrev":"bodegacdp"},
      {"name":"Bodega Bay CDP","abbrev":"bodegabaycdp"},
      {"name":"Bodfish CDP","abbrev":"bodfishcdp"},
      {"name":"Bolinas CDP","abbrev":"bolinascdp"},
      {"name":"Bombay Beach CDP","abbrev":"bombaybeachcdp"},
      {"name":"Bonadelle Ranchos-Madera Ranchos CDP","abbrev":"bonadelleranchos-maderaranchoscdp"},
      {"name":"Bonita CDP","abbrev":"bonitacdp"},
      {"name":"Bonny Doon CDP","abbrev":"bonnydooncdp"},
      {"name":"Bonsall CDP","abbrev":"bonsallcdp"},
      {"name":"Boonville CDP","abbrev":"boonvillecdp"},
      {"name":"Bootjack CDP","abbrev":"bootjackcdp"},
      {"name":"Boron CDP","abbrev":"boroncdp"},
      {"name":"Boronda CDP","abbrev":"borondacdp"},
      {"name":"Borrego Springs CDP","abbrev":"borregospringscdp"},
      {"name":"Bostonia CDP","abbrev":"bostoniacdp"},
      {"name":"Boulder Creek CDP","abbrev":"bouldercreekcdp"},
      {"name":"Boulevard CDP","abbrev":"boulevardcdp"},
      {"name":"Bowles CDP","abbrev":"bowlescdp"},
      {"name":"Boyes Hot Springs CDP","abbrev":"boyeshotspringscdp"},
      {"name":"Bradley CDP","abbrev":"bradleycdp"},
      {"name":"Bret Harte CDP","abbrev":"brethartecdp"},
      {"name":"Bridgeport CDP","abbrev":"bridgeportcdp"},
      {"name":"Broadmoor CDP","abbrev":"broadmoorcdp"},
      {"name":"Brookdale CDP","abbrev":"brookdalecdp"},
      {"name":"Brooktrails CDP","abbrev":"brooktrailscdp"},
      {"name":"Buckhorn CDP","abbrev":"buckhorncdp"},
      {"name":"Buck Meadows CDP","abbrev":"buckmeadowscdp"},
      {"name":"Bucks Lake CDP","abbrev":"buckslakecdp"},
      {"name":"Buena Vista CDP","abbrev":"buenavistacdp"},
      {"name":"Burbank CDP","abbrev":"burbankcdp"},
      {"name":"Burney CDP","abbrev":"burneycdp"},
      {"name":"Burnt Ranch CDP","abbrev":"burntranchcdp"},
      {"name":"Butte Creek Canyon CDP","abbrev":"buttecreekcanyoncdp"},
      {"name":"Butte Meadows CDP","abbrev":"buttemeadowscdp"},
      {"name":"Butte Valley CDP","abbrev":"buttevalleycdp"},
      {"name":"Buttonwillow CDP","abbrev":"buttonwillowcdp"},
      {"name":"Byron CDP","abbrev":"byroncdp"},
      {"name":"Bystrom CDP","abbrev":"bystromcdp"},
      {"name":"Cabazon CDP","abbrev":"cabazoncdp"},
      {"name":"California Hot Springs CDP","abbrev":"californiahotspringscdp"},
      {"name":"California Pines CDP","abbrev":"californiapinescdp"},
      {"name":"Callender CDP","abbrev":"callendercdp"},
      {"name":"Calpella CDP","abbrev":"calpellacdp"},
      {"name":"Calpine CDP","abbrev":"calpinecdp"},
      {"name":"Calwa CDP","abbrev":"calwacdp"},
      {"name":"Camanche North Shore CDP","abbrev":"camanchenorthshorecdp"},
      {"name":"Camanche Village CDP","abbrev":"camanchevillagecdp"},
      {"name":"Cambria CDP","abbrev":"cambriacdp"},
      {"name":"Cambrian Park CDP","abbrev":"cambrianparkcdp"},
      {"name":"Cameron Park CDP","abbrev":"cameronparkcdp"},
      {"name":"Camino CDP","abbrev":"caminocdp"},
      {"name":"Camino Tassajara CDP","abbrev":"caminotassajaracdp"},
      {"name":"Camp Nelson CDP","abbrev":"campnelsoncdp"},
      {"name":"Campo CDP","abbrev":"campocdp"},
      {"name":"Camp Pendleton North CDP","abbrev":"camppendletonnorthcdp"},
      {"name":"Camp Pendleton South CDP","abbrev":"camppendletonsouthcdp"},
      {"name":"Camptonville CDP","abbrev":"camptonvillecdp"},
      {"name":"Canby CDP","abbrev":"canbycdp"},
      {"name":"Cantua Creek CDP","abbrev":"cantuacreekcdp"},
      {"name":"Canyondam CDP","abbrev":"canyondamcdp"},
      {"name":"Caribou CDP","abbrev":"cariboucdp"},
      {"name":"Carmel Valley Village CDP","abbrev":"carmelvalleyvillagecdp"},
      {"name":"Carmet CDP","abbrev":"carmetcdp"},
      {"name":"Carmichael CDP","abbrev":"carmichaelcdp"},
      {"name":"Carnelian Bay CDP","abbrev":"carnelianbaycdp"},
      {"name":"Carrick CDP","abbrev":"carrickcdp"},
      {"name":"Cartago CDP","abbrev":"cartagocdp"},
      {"name":"Caruthers CDP","abbrev":"carutherscdp"},
      {"name":"Casa Conejo CDP","abbrev":"casaconejocdp"},
      {"name":"Casa de Oro-Mount Helix CDP","abbrev":"casadeoro-mounthelixcdp"},
      {"name":"Casmalia CDP","abbrev":"casmaliacdp"},
      {"name":"Caspar CDP","abbrev":"casparcdp"},
      {"name":"Cassel CDP","abbrev":"casselcdp"},
      {"name":"Castaic CDP","abbrev":"castaiccdp"},
      {"name":"Castle Hill CDP","abbrev":"castlehillcdp"},
      {"name":"Castro Valley CDP","abbrev":"castrovalleycdp"},
      {"name":"Castroville CDP","abbrev":"castrovillecdp"},
      {"name":"Catheys Valley CDP","abbrev":"catheysvalleycdp"},
      {"name":"Cayucos CDP","abbrev":"cayucoscdp"},
      {"name":"Cazadero CDP","abbrev":"cazaderocdp"},
      {"name":"Cedar Ridge CDP","abbrev":"cedarridgecdp"},
      {"name":"Cedar Slope CDP","abbrev":"cedarslopecdp"},
      {"name":"Cedarville CDP","abbrev":"cedarvillecdp"},
      {"name":"Centerville CDP","abbrev":"centervillecdp"},
      {"name":"Chalfant CDP","abbrev":"chalfantcdp"},
      {"name":"Challenge-Brownsville CDP","abbrev":"challenge-brownsvillecdp"},
      {"name":"Channel Islands Beach CDP","abbrev":"channelislandsbeachcdp"},
      {"name":"Charter Oak CDP","abbrev":"charteroakcdp"},
      {"name":"Cherokee CDP","abbrev":"cherokeecdp"},
      {"name":"Cherokee Strip CDP","abbrev":"cherokeestripcdp"},
      {"name":"Cherryland CDP","abbrev":"cherrylandcdp"},
      {"name":"Cherry Valley CDP","abbrev":"cherryvalleycdp"},
      {"name":"Chester CDP","abbrev":"chestercdp"},
      {"name":"Chilcoot-Vinton CDP","abbrev":"chilcoot-vintoncdp"},
      {"name":"China Lake Acres CDP","abbrev":"chinalakeacrescdp"},
      {"name":"Chinese Camp CDP","abbrev":"chinesecampcdp"},
      {"name":"Chualar CDP","abbrev":"chualarcdp"},
      {"name":"Citrus CDP","abbrev":"citruscdp"},
      {"name":"Clarksburg CDP","abbrev":"clarksburgcdp"},
      {"name":"Clay CDP","abbrev":"claycdp"},
      {"name":"Clear Creek CDP","abbrev":"clearcreekcdp"},
      {"name":"Clearlake Oaks CDP","abbrev":"clearlakeoakscdp"},
      {"name":"Clearlake Riviera CDP","abbrev":"clearlakerivieracdp"},
      {"name":"Cleone CDP","abbrev":"cleonecdp"},
      {"name":"Clio CDP","abbrev":"cliocdp"},
      {"name":"Clipper Mills CDP","abbrev":"clippermillscdp"},
      {"name":"Clyde CDP","abbrev":"clydecdp"},
      {"name":"Coarsegold CDP","abbrev":"coarsegoldcdp"},
      {"name":"Cobb CDP","abbrev":"cobbcdp"},
      {"name":"Coffee Creek CDP","abbrev":"coffeecreekcdp"},
      {"name":"Cohasset CDP","abbrev":"cohassetcdp"},
      {"name":"Cold Springs CDP","abbrev":"coldspringscdp"},
      {"name":"Cold Springs CDP","abbrev":"coldspringscdp"},
      {"name":"Coleville CDP","abbrev":"colevillecdp"},
      {"name":"College City CDP","abbrev":"collegecitycdp"},
      {"name":"Collierville CDP","abbrev":"colliervillecdp"},
      {"name":"Coloma CDP","abbrev":"colomacdp"},
      {"name":"Columbia CDP","abbrev":"columbiacdp"},
      {"name":"Comptche CDP","abbrev":"comptchecdp"},
      {"name":"Concow CDP","abbrev":"concowcdp"},
      {"name":"Contra Costa Centre CDP","abbrev":"contracostacentrecdp"},
      {"name":"Copperopolis CDP","abbrev":"copperopoliscdp"},
      {"name":"Coronita CDP","abbrev":"coronitacdp"},
      {"name":"Corralitos CDP","abbrev":"corralitoscdp"},
      {"name":"Coto de Caza CDP","abbrev":"cotodecazacdp"},
      {"name":"Cottonwood CDP","abbrev":"cottonwoodcdp"},
      {"name":"Coultervillle CDP","abbrev":"coultervilllecdp"},
      {"name":"Country Club CDP","abbrev":"countryclubcdp"},
      {"name":"Courtland CDP","abbrev":"courtlandcdp"},
      {"name":"Covelo CDP","abbrev":"covelocdp"},
      {"name":"Cowan CDP","abbrev":"cowancdp"},
      {"name":"Crescent Mills CDP","abbrev":"crescentmillscdp"},
      {"name":"Cressey CDP","abbrev":"cresseycdp"},
      {"name":"Crest CDP","abbrev":"crestcdp"},
      {"name":"Crestline CDP","abbrev":"crestlinecdp"},
      {"name":"Creston CDP","abbrev":"crestoncdp"},
      {"name":"C-Road CDP","abbrev":"c-roadcdp"},
      {"name":"Crockett CDP","abbrev":"crockettcdp"},
      {"name":"Cromberg CDP","abbrev":"crombergcdp"},
      {"name":"Crowley Lake CDP","abbrev":"crowleylakecdp"},
      {"name":"Crows Landing CDP","abbrev":"crowslandingcdp"},
      {"name":"Cutler CDP","abbrev":"cutlercdp"},
      {"name":"Cutten CDP","abbrev":"cuttencdp"},
      {"name":"Cuyama CDP","abbrev":"cuyamacdp"},
      {"name":"Daphnedale Park CDP","abbrev":"daphnedaleparkcdp"},
      {"name":"Darwin CDP","abbrev":"darwincdp"},
      {"name":"Davenport CDP","abbrev":"davenportcdp"},
      {"name":"Day Valley CDP","abbrev":"dayvalleycdp"},
      {"name":"Deer Park CDP","abbrev":"deerparkcdp"},
      {"name":"Del Aire CDP","abbrev":"delairecdp"},
      {"name":"Delft Colony CDP","abbrev":"delftcolonycdp"},
      {"name":"Delhi CDP","abbrev":"delhicdp"},
      {"name":"Delleker CDP","abbrev":"dellekercdp"},
      {"name":"Del Monte Forest CDP","abbrev":"delmonteforestcdp"},
      {"name":"Del Rey CDP","abbrev":"delreycdp"},
      {"name":"Del Rio CDP","abbrev":"delriocdp"},
      {"name":"Denair CDP","abbrev":"denaircdp"},
      {"name":"Derby Acres CDP","abbrev":"derbyacrescdp"},
      {"name":"Descanso CDP","abbrev":"descansocdp"},
      {"name":"Desert Center CDP","abbrev":"desertcentercdp"},
      {"name":"Desert Edge CDP","abbrev":"desertedgecdp"},
      {"name":"Desert Palms CDP","abbrev":"desertpalmscdp"},
      {"name":"Desert Shores CDP","abbrev":"desertshorescdp"},
      {"name":"Desert View Highlands CDP","abbrev":"desertviewhighlandscdp"},
      {"name":"Diablo CDP","abbrev":"diablocdp"},
      {"name":"Diablo Grande CDP","abbrev":"diablograndecdp"},
      {"name":"Diamond Springs CDP","abbrev":"diamondspringscdp"},
      {"name":"Dillon Beach CDP","abbrev":"dillonbeachcdp"},
      {"name":"Discovery Bay CDP","abbrev":"discoverybaycdp"},
      {"name":"Dixon Lane-Meadow Creek CDP","abbrev":"dixonlane-meadowcreekcdp"},
      {"name":"Dobbins CDP","abbrev":"dobbinscdp"},
      {"name":"Dogtown CDP","abbrev":"dogtowncdp"},
      {"name":"Dollar Point CDP","abbrev":"dollarpointcdp"},
      {"name":"Dorrington CDP","abbrev":"dorringtoncdp"},
      {"name":"Dos Palos Y CDP","abbrev":"dospalosycdp"},
      {"name":"Douglas City CDP","abbrev":"douglascitycdp"},
      {"name":"Downieville CDP","abbrev":"downievillecdp"},
      {"name":"Doyle CDP","abbrev":"doylecdp"},
      {"name":"Drytown CDP","abbrev":"drytowncdp"},
      {"name":"Ducor CDP","abbrev":"ducorcdp"},
      {"name":"Dunnigan CDP","abbrev":"dunnigancdp"},
      {"name":"Durham CDP","abbrev":"durhamcdp"},
      {"name":"Dustin Acres CDP","abbrev":"dustinacrescdp"},
      {"name":"Dutch Flat CDP","abbrev":"dutchflatcdp"},
      {"name":"Eagleville CDP","abbrev":"eaglevillecdp"},
      {"name":"Earlimart CDP","abbrev":"earlimartcdp"},
      {"name":"East Foothills CDP","abbrev":"eastfoothillscdp"},
      {"name":"East Hemet CDP","abbrev":"easthemetcdp"},
      {"name":"East Los Angeles CDP","abbrev":"eastlosangelescdp"},
      {"name":"East Nicolaus CDP","abbrev":"eastnicolauscdp"},
      {"name":"East Oakdale CDP","abbrev":"eastoakdalecdp"},
      {"name":"Easton CDP","abbrev":"eastoncdp"},
      {"name":"East Orosi CDP","abbrev":"eastorosicdp"},
      {"name":"East Pasadena CDP","abbrev":"eastpasadenacdp"},
      {"name":"East Porterville CDP","abbrev":"eastportervillecdp"},
      {"name":"East Quincy CDP","abbrev":"eastquincycdp"},
      {"name":"East Rancho Dominguez CDP","abbrev":"eastranchodominguezcdp"},
      {"name":"East Richmond Heights CDP","abbrev":"eastrichmondheightscdp"},
      {"name":"East San Gabriel CDP","abbrev":"eastsangabrielcdp"},
      {"name":"East Shore CDP","abbrev":"eastshorecdp"},
      {"name":"East Sonora CDP","abbrev":"eastsonoracdp"},
      {"name":"East Tulare Villa CDP","abbrev":"easttularevillacdp"},
      {"name":"East Whittier CDP","abbrev":"eastwhittiercdp"},
      {"name":"Edgewood CDP","abbrev":"edgewoodcdp"},
      {"name":"Edmundson Acres CDP","abbrev":"edmundsonacrescdp"},
      {"name":"Edna CDP","abbrev":"ednacdp"},
      {"name":"Edwards AFB CDP","abbrev":"edwardsafbcdp"},
      {"name":"El Cerrito CDP","abbrev":"elcerritocdp"},
      {"name":"El Dorado Hills CDP","abbrev":"eldoradohillscdp"},
      {"name":"Eldridge CDP","abbrev":"eldridgecdp"},
      {"name":"El Granada CDP","abbrev":"elgranadacdp"},
      {"name":"Elizabeth Lake CDP","abbrev":"elizabethlakecdp"},
      {"name":"Elk Creek CDP","abbrev":"elkcreekcdp"},
      {"name":"Elkhorn CDP","abbrev":"elkhorncdp"},
      {"name":"Elmira CDP","abbrev":"elmiracdp"},
      {"name":"El Nido CDP","abbrev":"elnidocdp"},
      {"name":"El Portal CDP","abbrev":"elportalcdp"},
      {"name":"El Rancho CDP","abbrev":"elranchocdp"},
      {"name":"El Rio CDP","abbrev":"elriocdp"},
      {"name":"El Sobrante CDP","abbrev":"elsobrantecdp"},
      {"name":"El Sobrante CDP","abbrev":"elsobrantecdp"},
      {"name":"El Verano CDP","abbrev":"elveranocdp"},
      {"name":"Elverta CDP","abbrev":"elvertacdp"},
      {"name":"Emerald Lake Hills CDP","abbrev":"emeraldlakehillscdp"},
      {"name":"Empire CDP","abbrev":"empirecdp"},
      {"name":"Esparto CDP","abbrev":"espartocdp"},
      {"name":"Eucalyptus Hills CDP","abbrev":"eucalyptushillscdp"},
      {"name":"Fairbanks Ranch CDP","abbrev":"fairbanksranchcdp"},
      {"name":"Fairmead CDP","abbrev":"fairmeadcdp"},
      {"name":"Fair Oaks CDP","abbrev":"fairoakscdp"},
      {"name":"Fairview CDP","abbrev":"fairviewcdp"},
      {"name":"Fallbrook CDP","abbrev":"fallbrookcdp"},
      {"name":"Fall River Mills CDP","abbrev":"fallrivermillscdp"},
      {"name":"Farmington CDP","abbrev":"farmingtoncdp"},
      {"name":"Fellows CDP","abbrev":"fellowscdp"},
      {"name":"Felton CDP","abbrev":"feltoncdp"},
      {"name":"Fetters Hot Springs-Agua Caliente CDP","abbrev":"fettershotsprings-aguacalientecdp"},
      {"name":"Fiddletown CDP","abbrev":"fiddletowncdp"},
      {"name":"Fieldbrook CDP","abbrev":"fieldbrookcdp"},
      {"name":"Fields Landing CDP","abbrev":"fieldslandingcdp"},
      {"name":"Fish Camp CDP","abbrev":"fishcampcdp"},
      {"name":"Florence-Graham CDP","abbrev":"florence-grahamcdp"},
      {"name":"Florin CDP","abbrev":"florincdp"},
      {"name":"Floriston CDP","abbrev":"floristoncdp"},
      {"name":"Flournoy CDP","abbrev":"flournoycdp"},
      {"name":"Foothill Farms CDP","abbrev":"foothillfarmscdp"},
      {"name":"Forbestown CDP","abbrev":"forbestowncdp"},
      {"name":"Ford City CDP","abbrev":"fordcitycdp"},
      {"name":"Foresthill CDP","abbrev":"foresthillcdp"},
      {"name":"Forest Meadows CDP","abbrev":"forestmeadowscdp"},
      {"name":"Forest Ranch CDP","abbrev":"forestranchcdp"},
      {"name":"Forestville CDP","abbrev":"forestvillecdp"},
      {"name":"Fort Bidwell CDP","abbrev":"fortbidwellcdp"},
      {"name":"Fort Irwin CDP","abbrev":"fortirwincdp"},
      {"name":"Fort Washington CDP","abbrev":"fortwashingtoncdp"},
      {"name":"Franklin CDP","abbrev":"franklincdp"},
      {"name":"Franklin CDP","abbrev":"franklincdp"},
      {"name":"Frazier Park CDP","abbrev":"frazierparkcdp"},
      {"name":"Freedom CDP","abbrev":"freedomcdp"},
      {"name":"Freeport CDP","abbrev":"freeportcdp"},
      {"name":"French Camp CDP","abbrev":"frenchcampcdp"},
      {"name":"French Gulch CDP","abbrev":"frenchgulchcdp"},
      {"name":"French Valley CDP","abbrev":"frenchvalleycdp"},
      {"name":"Friant CDP","abbrev":"friantcdp"},
      {"name":"Fruitdale CDP","abbrev":"fruitdalecdp"},
      {"name":"Fruitridge Pocket CDP","abbrev":"fruitridgepocketcdp"},
      {"name":"Fuller Acres CDP","abbrev":"fulleracrescdp"},
      {"name":"Fulton CDP","abbrev":"fultoncdp"},
      {"name":"Furnace Creek CDP","abbrev":"furnacecreekcdp"},
      {"name":"Garberville CDP","abbrev":"garbervillecdp"},
      {"name":"Garden Acres CDP","abbrev":"gardenacrescdp"},
      {"name":"Garden Farms CDP","abbrev":"gardenfarmscdp"},
      {"name":"Garey CDP","abbrev":"gareycdp"},
      {"name":"Garnet CDP","abbrev":"garnetcdp"},
      {"name":"Gasquet CDP","abbrev":"gasquetcdp"},
      {"name":"Gazelle CDP","abbrev":"gazellecdp"},
      {"name":"Georgetown CDP","abbrev":"georgetowncdp"},
      {"name":"Gerber CDP","abbrev":"gerbercdp"},
      {"name":"Geyserville CDP","abbrev":"geyservillecdp"},
      {"name":"Glen Ellen CDP","abbrev":"glenellencdp"},
      {"name":"Golden Hills CDP","abbrev":"goldenhillscdp"},
      {"name":"Gold Mountain CDP","abbrev":"goldmountaincdp"},
      {"name":"Gold River CDP","abbrev":"goldrivercdp"},
      {"name":"Good Hope CDP","abbrev":"goodhopecdp"},
      {"name":"Goodyears Bar CDP","abbrev":"goodyearsbarcdp"},
      {"name":"Goshen CDP","abbrev":"goshencdp"},
      {"name":"Graeagle CDP","abbrev":"graeaglecdp"},
      {"name":"Grangeville CDP","abbrev":"grangevillecdp"},
      {"name":"Granite Bay CDP","abbrev":"granitebaycdp"},
      {"name":"Granite Hills CDP","abbrev":"granitehillscdp"},
      {"name":"Graniteville CDP","abbrev":"granitevillecdp"},
      {"name":"Graton CDP","abbrev":"gratoncdp"},
      {"name":"Grayson CDP","abbrev":"graysoncdp"},
      {"name":"Greeley Hill CDP","abbrev":"greeleyhillcdp"},
      {"name":"Greenacres CDP","abbrev":"greenacrescdp"},
      {"name":"Green Acres CDP","abbrev":"greenacrescdp"},
      {"name":"Greenfield CDP","abbrev":"greenfieldcdp"},
      {"name":"Greenhorn CDP","abbrev":"greenhorncdp"},
      {"name":"Green Valley CDP","abbrev":"greenvalleycdp"},
      {"name":"Green Valley CDP","abbrev":"greenvalleycdp"},
      {"name":"Greenview CDP","abbrev":"greenviewcdp"},
      {"name":"Greenville CDP","abbrev":"greenvillecdp"},
      {"name":"Grenada CDP","abbrev":"grenadacdp"},
      {"name":"Grimes CDP","abbrev":"grimescdp"},
      {"name":"Grizzly Flats CDP","abbrev":"grizzlyflatscdp"},
      {"name":"Groveland CDP","abbrev":"grovelandcdp"},
      {"name":"Guerneville CDP","abbrev":"guernevillecdp"},
      {"name":"Guinda CDP","abbrev":"guindacdp"},
      {"name":"Hacienda Heights CDP","abbrev":"haciendaheightscdp"},
      {"name":"Hamilton Branch CDP","abbrev":"hamiltonbranchcdp"},
      {"name":"Hamilton City CDP","abbrev":"hamiltoncitycdp"},
      {"name":"Happy Camp CDP","abbrev":"happycampcdp"},
      {"name":"Harbison Canyon CDP","abbrev":"harbisoncanyoncdp"},
      {"name":"Hardwick CDP","abbrev":"hardwickcdp"},
      {"name":"Hartland CDP","abbrev":"hartlandcdp"},
      {"name":"Hartley CDP","abbrev":"hartleycdp"},
      {"name":"Hasley Canyon CDP","abbrev":"hasleycanyoncdp"},
      {"name":"Hat Creek CDP","abbrev":"hatcreekcdp"},
      {"name":"Hayfork CDP","abbrev":"hayforkcdp"},
      {"name":"Heber CDP","abbrev":"hebercdp"},
      {"name":"Herald CDP","abbrev":"heraldcdp"},
      {"name":"Herlong CDP","abbrev":"herlongcdp"},
      {"name":"Hickman CDP","abbrev":"hickmancdp"},
      {"name":"Hidden Meadows CDP","abbrev":"hiddenmeadowscdp"},
      {"name":"Hidden Valley Lake CDP","abbrev":"hiddenvalleylakecdp"},
      {"name":"Highgrove CDP","abbrev":"highgrovecdp"},
      {"name":"Highlands-Baywood Park CDP","abbrev":"highlands-baywoodparkcdp"},
      {"name":"Hilmar-Irwin CDP","abbrev":"hilmar-irwincdp"},
      {"name":"Hiouchi CDP","abbrev":"hiouchicdp"},
      {"name":"Home Garden CDP","abbrev":"homegardencdp"},
      {"name":"Home Gardens CDP","abbrev":"homegardenscdp"},
      {"name":"Homeland CDP","abbrev":"homelandcdp"},
      {"name":"Homestead Valley CDP","abbrev":"homesteadvalleycdp"},
      {"name":"Homewood Canyon CDP","abbrev":"homewoodcanyoncdp"},
      {"name":"Honcut CDP","abbrev":"honcutcdp"},
      {"name":"Hood CDP","abbrev":"hoodcdp"},
      {"name":"Hopland CDP","abbrev":"hoplandcdp"},
      {"name":"Hornbrook CDP","abbrev":"hornbrookcdp"},
      {"name":"Hornitos CDP","abbrev":"hornitoscdp"},
      {"name":"Humboldt Hill CDP","abbrev":"humboldthillcdp"},
      {"name":"Hyampom CDP","abbrev":"hyampomcdp"},
      {"name":"Hydesville CDP","abbrev":"hydesvillecdp"},
      {"name":"Idlewild CDP","abbrev":"idlewildcdp"},
      {"name":"Idyllwild-Pine Cove CDP","abbrev":"idyllwild-pinecovecdp"},
      {"name":"Independence CDP","abbrev":"independencecdp"},
      {"name":"Indian Falls CDP","abbrev":"indianfallscdp"},
      {"name":"Indianola CDP","abbrev":"indianolacdp"},
      {"name":"Indio Hills CDP","abbrev":"indiohillscdp"},
      {"name":"Interlaken CDP","abbrev":"interlakencdp"},
      {"name":"Inverness CDP","abbrev":"invernesscdp"},
      {"name":"Inyokern CDP","abbrev":"inyokerncdp"},
      {"name":"Iron Horse CDP","abbrev":"ironhorsecdp"},
      {"name":"Isla Vista CDP","abbrev":"islavistacdp"},
      {"name":"Ivanhoe CDP","abbrev":"ivanhoecdp"},
      {"name":"Jacumba CDP","abbrev":"jacumbacdp"},
      {"name":"Jamestown CDP","abbrev":"jamestowncdp"},
      {"name":"Jamul CDP","abbrev":"jamulcdp"},
      {"name":"Janesville CDP","abbrev":"janesvillecdp"},
      {"name":"Jenner CDP","abbrev":"jennercdp"},
      {"name":"Johannesburg CDP","abbrev":"johannesburgcdp"},
      {"name":"Johnstonville CDP","abbrev":"johnstonvillecdp"},
      {"name":"Johnsville CDP","abbrev":"johnsvillecdp"},
      {"name":"Joshua Tree CDP","abbrev":"joshuatreecdp"},
      {"name":"Julian CDP","abbrev":"juliancdp"},
      {"name":"Junction City CDP","abbrev":"junctioncitycdp"},
      {"name":"June Lake CDP","abbrev":"junelakecdp"},
      {"name":"Keddie CDP","abbrev":"keddiecdp"},
      {"name":"Keeler CDP","abbrev":"keelercdp"},
      {"name":"Keene CDP","abbrev":"keenecdp"},
      {"name":"Kelly Ridge CDP","abbrev":"kellyridgecdp"},
      {"name":"Kelseyville CDP","abbrev":"kelseyvillecdp"},
      {"name":"Kennedy CDP","abbrev":"kennedycdp"},
      {"name":"Kennedy Meadows CDP","abbrev":"kennedymeadowscdp"},
      {"name":"Kensington CDP","abbrev":"kensingtoncdp"},
      {"name":"Kentfield CDP","abbrev":"kentfieldcdp"},
      {"name":"Kenwood CDP","abbrev":"kenwoodcdp"},
      {"name":"Kernville CDP","abbrev":"kernvillecdp"},
      {"name":"Keswick CDP","abbrev":"keswickcdp"},
      {"name":"Kettleman City CDP","abbrev":"kettlemancitycdp"},
      {"name":"Keyes CDP","abbrev":"keyescdp"},
      {"name":"Kings Beach CDP","abbrev":"kingsbeachcdp"},
      {"name":"Kingvale CDP","abbrev":"kingvalecdp"},
      {"name":"Kirkwood CDP","abbrev":"kirkwoodcdp"},
      {"name":"Klamath CDP","abbrev":"klamathcdp"},
      {"name":"Knightsen CDP","abbrev":"knightsencdp"},
      {"name":"Knights Landing CDP","abbrev":"knightslandingcdp"},
      {"name":"La Crescenta-Montrose CDP","abbrev":"lacrescenta-montrosecdp"},
      {"name":"Ladera CDP","abbrev":"laderacdp"},
      {"name":"Ladera Heights CDP","abbrev":"laderaheightscdp"},
      {"name":"Ladera Ranch CDP","abbrev":"laderaranchcdp"},
      {"name":"Lagunitas-Forest Knolls CDP","abbrev":"lagunitas-forestknollscdp"},
      {"name":"La Honda CDP","abbrev":"lahondacdp"},
      {"name":"Lake Almanor Country Club CDP","abbrev":"lakealmanorcountryclubcdp"},
      {"name":"Lake Almanor Peninsula CDP","abbrev":"lakealmanorpeninsulacdp"},
      {"name":"Lake Almanor West CDP","abbrev":"lakealmanorwestcdp"},
      {"name":"Lake Arrowhead CDP","abbrev":"lakearrowheadcdp"},
      {"name":"Lake California CDP","abbrev":"lakecaliforniacdp"},
      {"name":"Lake City CDP","abbrev":"lakecitycdp"},
      {"name":"Lake Davis CDP","abbrev":"lakedaviscdp"},
      {"name":"Lake Don Pedro CDP","abbrev":"lakedonpedrocdp"},
      {"name":"Lakehead CDP","abbrev":"lakeheadcdp"},
      {"name":"Lake Hughes CDP","abbrev":"lakehughescdp"},
      {"name":"Lake Isabella CDP","abbrev":"lakeisabellacdp"},
      {"name":"Lakeland Village CDP","abbrev":"lakelandvillagecdp"},
      {"name":"Lake Los Angeles CDP","abbrev":"lakelosangelescdp"},
      {"name":"Lake Mathews CDP","abbrev":"lakemathewscdp"},
      {"name":"Lake Nacimiento CDP","abbrev":"lakenacimientocdp"},
      {"name":"Lake of the Pines CDP","abbrev":"lakeofthepinescdp"},
      {"name":"Lake of the Woods CDP","abbrev":"lakeofthewoodscdp"},
      {"name":"Lake Riverside CDP","abbrev":"lakeriversidecdp"},
      {"name":"Lake San Marcos CDP","abbrev":"lakesanmarcoscdp"},
      {"name":"Lake Sherwood CDP","abbrev":"lakesherwoodcdp"},
      {"name":"Lakeside CDP","abbrev":"lakesidecdp"},
      {"name":"Lakeview CDP","abbrev":"lakeviewcdp"},
      {"name":"Lake Wildwood CDP","abbrev":"lakewildwoodcdp"},
      {"name":"Lamont CDP","abbrev":"lamontcdp"},
      {"name":"Lanare CDP","abbrev":"lanarecdp"},
      {"name":"La Porte CDP","abbrev":"laportecdp"},
      {"name":"La Presa CDP","abbrev":"lapresacdp"},
      {"name":"La Riviera CDP","abbrev":"larivieracdp"},
      {"name":"Larkfield-Wikiup CDP","abbrev":"larkfield-wikiupcdp"},
      {"name":"La Selva Beach CDP","abbrev":"laselvabeachcdp"},
      {"name":"Las Flores CDP","abbrev":"lasflorescdp"},
      {"name":"Las Flores CDP","abbrev":"lasflorescdp"},
      {"name":"Las Lomas CDP","abbrev":"laslomascdp"},
      {"name":"Laton CDP","abbrev":"latoncdp"},
      {"name":"La Vina CDP","abbrev":"lavinacdp"},
      {"name":"Laytonville CDP","abbrev":"laytonvillecdp"},
      {"name":"Lebec CDP","abbrev":"lebeccdp"},
      {"name":"Lee Vining CDP","abbrev":"leeviningcdp"},
      {"name":"Leggett CDP","abbrev":"leggettcdp"},
      {"name":"Le Grand CDP","abbrev":"legrandcdp"},
      {"name":"Lemon Cove CDP","abbrev":"lemoncovecdp"},
      {"name":"Lemon Hill CDP","abbrev":"lemonhillcdp"},
      {"name":"Lemoore Station CDP","abbrev":"lemoorestationcdp"},
      {"name":"Lennox CDP","abbrev":"lennoxcdp"},
      {"name":"Lenwood CDP","abbrev":"lenwoodcdp"},
      {"name":"Leona Valley CDP","abbrev":"leonavalleycdp"},
      {"name":"Lewiston CDP","abbrev":"lewistoncdp"},
      {"name":"Lexington Hills CDP","abbrev":"lexingtonhillscdp"},
      {"name":"Likely CDP","abbrev":"likelycdp"},
      {"name":"Lincoln Village CDP","abbrev":"lincolnvillagecdp"},
      {"name":"Linda CDP","abbrev":"lindacdp"},
      {"name":"Lindcove CDP","abbrev":"lindcovecdp"},
      {"name":"Linden CDP","abbrev":"lindencdp"},
      {"name":"Linnell Camp CDP","abbrev":"linnellcampcdp"},
      {"name":"Litchfield CDP","abbrev":"litchfieldcdp"},
      {"name":"Little Grass Valley CDP","abbrev":"littlegrassvalleycdp"},
      {"name":"Little River CDP","abbrev":"littlerivercdp"},
      {"name":"Littlerock CDP","abbrev":"littlerockcdp"},
      {"name":"Live Oak CDP","abbrev":"liveoakcdp"},
      {"name":"Lockeford CDP","abbrev":"lockefordcdp"},
      {"name":"Lockwood CDP","abbrev":"lockwoodcdp"},
      {"name":"Lodoga CDP","abbrev":"lodogacdp"},
      {"name":"Loleta CDP","abbrev":"loletacdp"},
      {"name":"Loma Mar CDP","abbrev":"lomamarcdp"},
      {"name":"Loma Rica CDP","abbrev":"lomaricacdp"},
      {"name":"Lompico CDP","abbrev":"lompicocdp"},
      {"name":"London CDP","abbrev":"londoncdp"},
      {"name":"Lone Pine CDP","abbrev":"lonepinecdp"},
      {"name":"Long Barn CDP","abbrev":"longbarncdp"},
      {"name":"Lookout CDP","abbrev":"lookoutcdp"},
      {"name":"Los Alamos CDP","abbrev":"losalamoscdp"},
      {"name":"Los Berros CDP","abbrev":"losberroscdp"},
      {"name":"Los Molinos CDP","abbrev":"losmolinoscdp"},
      {"name":"Los Olivos CDP","abbrev":"losolivoscdp"},
      {"name":"Los Osos CDP","abbrev":"losososcdp"},
      {"name":"Los Ranchos CDP","abbrev":"losranchoscdp"},
      {"name":"Lost Hills CDP","abbrev":"losthillscdp"},
      {"name":"Lower Lake CDP","abbrev":"lowerlakecdp"},
      {"name":"Loyola CDP","abbrev":"loyolacdp"},
      {"name":"Lucas Valley-Marinwood CDP","abbrev":"lucasvalley-marinwoodcdp"},
      {"name":"Lucerne CDP","abbrev":"lucernecdp"},
      {"name":"Lucerne Valley CDP","abbrev":"lucernevalleycdp"},
      {"name":"Lytle Creek CDP","abbrev":"lytlecreekcdp"},
      {"name":"Mabie CDP","abbrev":"mabiecdp"},
      {"name":"McArthur CDP","abbrev":"mcarthurcdp"},
      {"name":"McClellan Park CDP","abbrev":"mcclellanparkcdp"},
      {"name":"McClenney Tract CDP","abbrev":"mcclenneytractcdp"},
      {"name":"McCloud CDP","abbrev":"mccloudcdp"},
      {"name":"Macdoel CDP","abbrev":"macdoelcdp"},
      {"name":"McGee Creek CDP","abbrev":"mcgeecreekcdp"},
      {"name":"McKinleyville CDP","abbrev":"mckinleyvillecdp"},
      {"name":"McKittrick CDP","abbrev":"mckittrickcdp"},
      {"name":"McSwain CDP","abbrev":"mcswaincdp"},
      {"name":"Madera Acres CDP","abbrev":"maderaacrescdp"},
      {"name":"Madison CDP","abbrev":"madisoncdp"},
      {"name":"Mad River CDP","abbrev":"madrivercdp"},
      {"name":"Magalia CDP","abbrev":"magaliacdp"},
      {"name":"Malaga CDP","abbrev":"malagacdp"},
      {"name":"Manchester CDP","abbrev":"manchestercdp"},
      {"name":"Manila CDP","abbrev":"manilacdp"},
      {"name":"Manton CDP","abbrev":"mantoncdp"},
      {"name":"March ARB CDP","abbrev":"marcharbcdp"},
      {"name":"Marina del Rey CDP","abbrev":"marinadelreycdp"},
      {"name":"Marin City CDP","abbrev":"marincitycdp"},
      {"name":"Mariposa CDP","abbrev":"mariposacdp"},
      {"name":"Markleeville CDP","abbrev":"markleevillecdp"},
      {"name":"Martell CDP","abbrev":"martellcdp"},
      {"name":"Matheny CDP","abbrev":"mathenycdp"},
      {"name":"Mather CDP","abbrev":"mathercdp"},
      {"name":"Maxwell CDP","abbrev":"maxwellcdp"},
      {"name":"Mayfair CDP","abbrev":"mayfaircdp"},
      {"name":"Mayflower Village CDP","abbrev":"mayflowervillagecdp"},
      {"name":"Meadowbrook CDP","abbrev":"meadowbrookcdp"},
      {"name":"Meadow Valley CDP","abbrev":"meadowvalleycdp"},
      {"name":"Meadow Vista CDP","abbrev":"meadowvistacdp"},
      {"name":"Mead Valley CDP","abbrev":"meadvalleycdp"},
      {"name":"Mecca CDP","abbrev":"meccacdp"},
      {"name":"Meiners Oaks CDP","abbrev":"meinersoakscdp"},
      {"name":"Mendocino CDP","abbrev":"mendocinocdp"},
      {"name":"Mentone CDP","abbrev":"mentonecdp"},
      {"name":"Meridian CDP","abbrev":"meridiancdp"},
      {"name":"Mesa CDP","abbrev":"mesacdp"},
      {"name":"Mesa Verde CDP","abbrev":"mesaverdecdp"},
      {"name":"Mesa Vista CDP","abbrev":"mesavistacdp"},
      {"name":"Mettler CDP","abbrev":"mettlercdp"},
      {"name":"Mexican Colony CDP","abbrev":"mexicancolonycdp"},
      {"name":"Middletown CDP","abbrev":"middletowncdp"},
      {"name":"Midpines CDP","abbrev":"midpinescdp"},
      {"name":"Midway City CDP","abbrev":"midwaycitycdp"},
      {"name":"Milford CDP","abbrev":"milfordcdp"},
      {"name":"Millville CDP","abbrev":"millvillecdp"},
      {"name":"Mineral CDP","abbrev":"mineralcdp"},
      {"name":"Minkler CDP","abbrev":"minklercdp"},
      {"name":"Mira Monte CDP","abbrev":"miramontecdp"},
      {"name":"Miranda CDP","abbrev":"mirandacdp"},
      {"name":"Mission Canyon CDP","abbrev":"missioncanyoncdp"},
      {"name":"Mission Hills CDP","abbrev":"missionhillscdp"},
      {"name":"Mi-Wuk Village CDP","abbrev":"mi-wukvillagecdp"},
      {"name":"Mohawk Vista CDP","abbrev":"mohawkvistacdp"},
      {"name":"Mojave CDP","abbrev":"mojavecdp"},
      {"name":"Mokelumne Hill CDP","abbrev":"mokelumnehillcdp"},
      {"name":"Monmouth CDP","abbrev":"monmouthcdp"},
      {"name":"Mono City CDP","abbrev":"monocitycdp"},
      {"name":"Mono Vista CDP","abbrev":"monovistacdp"},
      {"name":"Monson CDP","abbrev":"monsoncdp"},
      {"name":"Montalvin Manor CDP","abbrev":"montalvinmanorcdp"},
      {"name":"Montara CDP","abbrev":"montaracdp"},
      {"name":"Montecito CDP","abbrev":"montecitocdp"},
      {"name":"Monterey Park Tract CDP","abbrev":"montereyparktractcdp"},
      {"name":"Monte Rio CDP","abbrev":"monteriocdp"},
      {"name":"Montgomery Creek CDP","abbrev":"montgomerycreekcdp"},
      {"name":"Monument Hills CDP","abbrev":"monumenthillscdp"},
      {"name":"Morada CDP","abbrev":"moradacdp"},
      {"name":"Morongo Valley CDP","abbrev":"morongovalleycdp"},
      {"name":"Moskowite Corner CDP","abbrev":"moskowitecornercdp"},
      {"name":"Moss Beach CDP","abbrev":"mossbeachcdp"},
      {"name":"Moss Landing CDP","abbrev":"mosslandingcdp"},
      {"name":"Mountain Center CDP","abbrev":"mountaincentercdp"},
      {"name":"Mountain Gate CDP","abbrev":"mountaingatecdp"},
      {"name":"Mountain House CDP","abbrev":"mountainhousecdp"},
      {"name":"Mountain Mesa CDP","abbrev":"mountainmesacdp"},
      {"name":"Mountain Ranch CDP","abbrev":"mountainranchcdp"},
      {"name":"Mountain View CDP","abbrev":"mountainviewcdp"},
      {"name":"Mountain View Acres CDP","abbrev":"mountainviewacrescdp"},
      {"name":"Mount Hebron CDP","abbrev":"mounthebroncdp"},
      {"name":"Mount Hermon CDP","abbrev":"mounthermoncdp"},
      {"name":"Mount Laguna CDP","abbrev":"mountlagunacdp"},
      {"name":"Muir Beach CDP","abbrev":"muirbeachcdp"},
      {"name":"Murphys CDP","abbrev":"murphyscdp"},
      {"name":"Muscoy CDP","abbrev":"muscoycdp"},
      {"name":"Myers Flat CDP","abbrev":"myersflatcdp"},
      {"name":"Myrtletown CDP","abbrev":"myrtletowncdp"},
      {"name":"Newcastle CDP","abbrev":"newcastlecdp"},
      {"name":"New Cuyama CDP","abbrev":"newcuyamacdp"},
      {"name":"Newell CDP","abbrev":"newellcdp"},
      {"name":"New Pine Creek CDP","abbrev":"newpinecreekcdp"},
      {"name":"Nicasio CDP","abbrev":"nicasiocdp"},
      {"name":"Nice CDP","abbrev":"nicecdp"},
      {"name":"Nicolaus CDP","abbrev":"nicolauscdp"},
      {"name":"Niland CDP","abbrev":"nilandcdp"},
      {"name":"Nipinnawasee CDP","abbrev":"nipinnawaseecdp"},
      {"name":"Nipomo CDP","abbrev":"nipomocdp"},
      {"name":"Nord CDP","abbrev":"nordcdp"},
      {"name":"Norris Canyon CDP","abbrev":"norriscanyoncdp"},
      {"name":"North Auburn CDP","abbrev":"northauburncdp"},
      {"name":"North Edwards CDP","abbrev":"northedwardscdp"},
      {"name":"North El Monte CDP","abbrev":"northelmontecdp"},
      {"name":"North Fair Oaks CDP","abbrev":"northfairoakscdp"},
      {"name":"North Gate CDP","abbrev":"northgatecdp"},
      {"name":"North Highlands CDP","abbrev":"northhighlandscdp"},
      {"name":"North Lakeport CDP","abbrev":"northlakeportcdp"},
      {"name":"North Richmond CDP","abbrev":"northrichmondcdp"},
      {"name":"North San Juan CDP","abbrev":"northsanjuancdp"},
      {"name":"North Shore CDP","abbrev":"northshorecdp"},
      {"name":"North Tustin CDP","abbrev":"northtustincdp"},
      {"name":"Nubieber CDP","abbrev":"nubiebercdp"},
      {"name":"Nuevo CDP","abbrev":"nuevocdp"},
      {"name":"Oak Glen CDP","abbrev":"oakglencdp"},
      {"name":"Oak Hills CDP","abbrev":"oakhillscdp"},
      {"name":"Oakhurst CDP","abbrev":"oakhurstcdp"},
      {"name":"Oak Park CDP","abbrev":"oakparkcdp"},
      {"name":"Oak Shores CDP","abbrev":"oakshorescdp"},
      {"name":"Oak View CDP","abbrev":"oakviewcdp"},
      {"name":"Oakville CDP","abbrev":"oakvillecdp"},
      {"name":"Oasis CDP","abbrev":"oasiscdp"},
      {"name":"Occidental CDP","abbrev":"occidentalcdp"},
      {"name":"Oceano CDP","abbrev":"oceanocdp"},
      {"name":"Ocotillo CDP","abbrev":"ocotillocdp"},
      {"name":"Oildale CDP","abbrev":"oildalecdp"},
      {"name":"Olancha CDP","abbrev":"olanchacdp"},
      {"name":"Old Fig Garden CDP","abbrev":"oldfiggardencdp"},
      {"name":"Old Station CDP","abbrev":"oldstationcdp"},
      {"name":"Olivehurst CDP","abbrev":"olivehurstcdp"},
      {"name":"Onyx CDP","abbrev":"onyxcdp"},
      {"name":"Orangevale CDP","abbrev":"orangevalecdp"},
      {"name":"Orcutt CDP","abbrev":"orcuttcdp"},
      {"name":"Orick CDP","abbrev":"orickcdp"},
      {"name":"Orosi CDP","abbrev":"orosicdp"},
      {"name":"Oroville East CDP","abbrev":"orovilleeastcdp"},
      {"name":"Pacheco CDP","abbrev":"pachecocdp"},
      {"name":"Pajaro CDP","abbrev":"pajarocdp"},
      {"name":"Pajaro Dunes CDP","abbrev":"pajarodunescdp"},
      {"name":"Palermo CDP","abbrev":"palermocdp"},
      {"name":"Palo Cedro CDP","abbrev":"palocedrocdp"},
      {"name":"Palo Verde CDP","abbrev":"paloverdecdp"},
      {"name":"Panorama Heights CDP","abbrev":"panoramaheightscdp"},
      {"name":"Paradise CDP","abbrev":"paradisecdp"},
      {"name":"Paradise Park CDP","abbrev":"paradiseparkcdp"},
      {"name":"Parklawn CDP","abbrev":"parklawncdp"},
      {"name":"Parksdale CDP","abbrev":"parksdalecdp"},
      {"name":"Parkway CDP","abbrev":"parkwaycdp"},
      {"name":"Parkwood CDP","abbrev":"parkwoodcdp"},
      {"name":"Pasatiempo CDP","abbrev":"pasatiempocdp"},
      {"name":"Paskenta CDP","abbrev":"paskentacdp"},
      {"name":"Patterson Tract CDP","abbrev":"pattersontractcdp"},
      {"name":"Patton Village CDP","abbrev":"pattonvillagecdp"},
      {"name":"Paxton CDP","abbrev":"paxtoncdp"},
      {"name":"Paynes Creek CDP","abbrev":"paynescreekcdp"},
      {"name":"Pearsonville CDP","abbrev":"pearsonvillecdp"},
      {"name":"Penngrove CDP","abbrev":"penngrovecdp"},
      {"name":"Penn Valley CDP","abbrev":"pennvalleycdp"},
      {"name":"Penryn CDP","abbrev":"penryncdp"},
      {"name":"Pescadero CDP","abbrev":"pescaderocdp"},
      {"name":"Peters CDP","abbrev":"peterscdp"},
      {"name":"Phelan CDP","abbrev":"phelancdp"},
      {"name":"Phillipsville CDP","abbrev":"phillipsvillecdp"},
      {"name":"Philo CDP","abbrev":"philocdp"},
      {"name":"Phoenix Lake CDP","abbrev":"phoenixlakecdp"},
      {"name":"Pierpoint CDP","abbrev":"pierpointcdp"},
      {"name":"Pike CDP","abbrev":"pikecdp"},
      {"name":"Pine Canyon CDP","abbrev":"pinecanyoncdp"},
      {"name":"Pine Flat CDP","abbrev":"pineflatcdp"},
      {"name":"Pine Grove CDP","abbrev":"pinegrovecdp"},
      {"name":"Pine Hills CDP","abbrev":"pinehillscdp"},
      {"name":"Pine Mountain Club CDP","abbrev":"pinemountainclubcdp"},
      {"name":"Pine Mountain Lake CDP","abbrev":"pinemountainlakecdp"},
      {"name":"Pine Valley CDP","abbrev":"pinevalleycdp"},
      {"name":"Pion Hills CDP","abbrev":"pionhillscdp"},
      {"name":"Pioneer CDP","abbrev":"pioneercdp"},
      {"name":"Piru CDP","abbrev":"pirucdp"},
      {"name":"Pixley CDP","abbrev":"pixleycdp"},
      {"name":"Plainview CDP","abbrev":"plainviewcdp"},
      {"name":"Planada CDP","abbrev":"planadacdp"},
      {"name":"Pleasure Point CDP","abbrev":"pleasurepointcdp"},
      {"name":"Plumas Eureka CDP","abbrev":"plumaseurekacdp"},
      {"name":"Plumas Lake CDP","abbrev":"plumaslakecdp"},
      {"name":"Point Reyes Station CDP","abbrev":"pointreyesstationcdp"},
      {"name":"Pollock Pines CDP","abbrev":"pollockpinescdp"},
      {"name":"Ponderosa CDP","abbrev":"ponderosacdp"},
      {"name":"Poplar-Cotton Center CDP","abbrev":"poplar-cottoncentercdp"},
      {"name":"Port Costa CDP","abbrev":"portcostacdp"},
      {"name":"Posey CDP","abbrev":"poseycdp"},
      {"name":"Poso Park CDP","abbrev":"posoparkcdp"},
      {"name":"Potrero CDP","abbrev":"potrerocdp"},
      {"name":"Potter Valley CDP","abbrev":"pottervalleycdp"},
      {"name":"Prattville CDP","abbrev":"prattvillecdp"},
      {"name":"Princeton CDP","abbrev":"princetoncdp"},
      {"name":"Proberta CDP","abbrev":"probertacdp"},
      {"name":"Prunedale CDP","abbrev":"prunedalecdp"},
      {"name":"Quartz Hill CDP","abbrev":"quartzhillcdp"},
      {"name":"Quincy CDP","abbrev":"quincycdp"},
      {"name":"Rackerby CDP","abbrev":"rackerbycdp"},
      {"name":"Rail Road Flat CDP","abbrev":"railroadflatcdp"},
      {"name":"Rainbow CDP","abbrev":"rainbowcdp"},
      {"name":"Raisin City CDP","abbrev":"raisincitycdp"},
      {"name":"Ramona CDP","abbrev":"ramonacdp"},
      {"name":"Rancho Calaveras CDP","abbrev":"ranchocalaverascdp"},
      {"name":"Rancho Murieta CDP","abbrev":"ranchomurietacdp"},
      {"name":"Rancho San Diego CDP","abbrev":"ranchosandiegocdp"},
      {"name":"Rancho Santa Fe CDP","abbrev":"ranchosantafecdp"},
      {"name":"Rancho Tehama Reserve CDP","abbrev":"ranchotehamareservecdp"},
      {"name":"Randsburg CDP","abbrev":"randsburgcdp"},
      {"name":"Red Corral CDP","abbrev":"redcorralcdp"},
      {"name":"Redcrest CDP","abbrev":"redcrestcdp"},
      {"name":"Redway CDP","abbrev":"redwaycdp"},
      {"name":"Redwood Valley CDP","abbrev":"redwoodvalleycdp"},
      {"name":"Reliez Valley CDP","abbrev":"reliezvalleycdp"},
      {"name":"Richfield CDP","abbrev":"richfieldcdp"},
      {"name":"Richgrove CDP","abbrev":"richgrovecdp"},
      {"name":"Richvale CDP","abbrev":"richvalecdp"},
      {"name":"Ridgemark CDP","abbrev":"ridgemarkcdp"},
      {"name":"Rio del Mar CDP","abbrev":"riodelmarcdp"},
      {"name":"Rio Linda CDP","abbrev":"riolindacdp"},
      {"name":"Rio Oso CDP","abbrev":"rioosocdp"},
      {"name":"Ripley CDP","abbrev":"ripleycdp"},
      {"name":"Riverdale CDP","abbrev":"riverdalecdp"},
      {"name":"Riverdale Park CDP","abbrev":"riverdaleparkcdp"},
      {"name":"River Pines CDP","abbrev":"riverpinescdp"},
      {"name":"Robbins CDP","abbrev":"robbinscdp"},
      {"name":"Robinson Mill CDP","abbrev":"robinsonmillcdp"},
      {"name":"Rodeo CDP","abbrev":"rodeocdp"},
      {"name":"Rodriguez Camp CDP","abbrev":"rodriguezcampcdp"},
      {"name":"Rolling Hills CDP","abbrev":"rollinghillscdp"},
      {"name":"Rollingwood CDP","abbrev":"rollingwoodcdp"},
      {"name":"Romoland CDP","abbrev":"romolandcdp"},
      {"name":"Rosamond CDP","abbrev":"rosamondcdp"},
      {"name":"Rosedale CDP","abbrev":"rosedalecdp"},
      {"name":"Rose Hills CDP","abbrev":"rosehillscdp"},
      {"name":"Roseland CDP","abbrev":"roselandcdp"},
      {"name":"Rosemont CDP","abbrev":"rosemontcdp"},
      {"name":"Rossmoor CDP","abbrev":"rossmoorcdp"},
      {"name":"Rough and Ready CDP","abbrev":"roughandreadycdp"},
      {"name":"Round Mountain CDP","abbrev":"roundmountaincdp"},
      {"name":"Round Valley CDP","abbrev":"roundvalleycdp"},
      {"name":"Rouse CDP","abbrev":"rousecdp"},
      {"name":"Rowland Heights CDP","abbrev":"rowlandheightscdp"},
      {"name":"Running Springs CDP","abbrev":"runningspringscdp"},
      {"name":"Ruth CDP","abbrev":"ruthcdp"},
      {"name":"Rutherford CDP","abbrev":"rutherfordcdp"},
      {"name":"Salida CDP","abbrev":"salidacdp"},
      {"name":"Salmon Creek CDP","abbrev":"salmoncreekcdp"},
      {"name":"Salton City CDP","abbrev":"saltoncitycdp"},
      {"name":"Salton Sea Beach CDP","abbrev":"saltonseabeachcdp"},
      {"name":"Samoa CDP","abbrev":"samoacdp"},
      {"name":"San Andreas CDP","abbrev":"sanandreascdp"},
      {"name":"San Antonio Heights CDP","abbrev":"sanantonioheightscdp"},
      {"name":"San Ardo CDP","abbrev":"sanardocdp"},
      {"name":"San Diego Country Estates CDP","abbrev":"sandiegocountryestatescdp"},
      {"name":"San Geronimo CDP","abbrev":"sangeronimocdp"},
      {"name":"San Lorenzo CDP","abbrev":"sanlorenzocdp"},
      {"name":"San Lucas CDP","abbrev":"sanlucascdp"},
      {"name":"San Martin CDP","abbrev":"sanmartincdp"},
      {"name":"San Miguel CDP","abbrev":"sanmiguelcdp"},
      {"name":"San Miguel CDP","abbrev":"sanmiguelcdp"},
      {"name":"San Pasqual CDP","abbrev":"sanpasqualcdp"},
      {"name":"San Simeon CDP","abbrev":"sansimeoncdp"},
      {"name":"Santa Margarita CDP","abbrev":"santamargaritacdp"},
      {"name":"Santa Nella CDP","abbrev":"santanellacdp"},
      {"name":"Santa Rosa Valley CDP","abbrev":"santarosavalleycdp"},
      {"name":"Santa Susana CDP","abbrev":"santasusanacdp"},
      {"name":"Santa Venetia CDP","abbrev":"santavenetiacdp"},
      {"name":"Santa Ynez CDP","abbrev":"santaynezcdp"},
      {"name":"Saranap CDP","abbrev":"saranapcdp"},
      {"name":"Saticoy CDP","abbrev":"saticoycdp"},
      {"name":"Sattley CDP","abbrev":"sattleycdp"},
      {"name":"Scotia CDP","abbrev":"scotiacdp"},
      {"name":"Seacliff CDP","abbrev":"seacliffcdp"},
      {"name":"Sea Ranch CDP","abbrev":"searanchcdp"},
      {"name":"Searles Valley CDP","abbrev":"searlesvalleycdp"},
      {"name":"Seeley CDP","abbrev":"seeleycdp"},
      {"name":"Sequoia Crest CDP","abbrev":"sequoiacrestcdp"},
      {"name":"Sereno del Mar CDP","abbrev":"serenodelmarcdp"},
      {"name":"Seville CDP","abbrev":"sevillecdp"},
      {"name":"Shackelford CDP","abbrev":"shackelfordcdp"},
      {"name":"Shandon CDP","abbrev":"shandoncdp"},
      {"name":"Shasta CDP","abbrev":"shastacdp"},
      {"name":"Shaver Lake CDP","abbrev":"shaverlakecdp"},
      {"name":"Shell Ridge CDP","abbrev":"shellridgecdp"},
      {"name":"Shelter Cove CDP","abbrev":"sheltercovecdp"},
      {"name":"Sheridan CDP","abbrev":"sheridancdp"},
      {"name":"Shingle Springs CDP","abbrev":"shinglespringscdp"},
      {"name":"Shingletown CDP","abbrev":"shingletowncdp"},
      {"name":"Shoshone CDP","abbrev":"shoshonecdp"},
      {"name":"Sierra Brooks CDP","abbrev":"sierrabrookscdp"},
      {"name":"Sierra City CDP","abbrev":"sierracitycdp"},
      {"name":"Sierra Village CDP","abbrev":"sierravillagecdp"},
      {"name":"Sierraville CDP","abbrev":"sierravillecdp"},
      {"name":"Silverado Resort CDP","abbrev":"silveradoresortcdp"},
      {"name":"Silver City CDP","abbrev":"silvercitycdp"},
      {"name":"Silver Lakes CDP","abbrev":"silverlakescdp"},
      {"name":"Sisquoc CDP","abbrev":"sisquoccdp"},
      {"name":"Sky Valley CDP","abbrev":"skyvalleycdp"},
      {"name":"Sleepy Hollow CDP","abbrev":"sleepyhollowcdp"},
      {"name":"Smartsville CDP","abbrev":"smartsvillecdp"},
      {"name":"Smith Corner CDP","abbrev":"smithcornercdp"},
      {"name":"Smith River CDP","abbrev":"smithrivercdp"},
      {"name":"Snelling CDP","abbrev":"snellingcdp"},
      {"name":"Soda Bay CDP","abbrev":"sodabaycdp"},
      {"name":"Soda Springs CDP","abbrev":"sodaspringscdp"},
      {"name":"Soquel CDP","abbrev":"soquelcdp"},
      {"name":"Soulsbyville CDP","abbrev":"soulsbyvillecdp"},
      {"name":"South Dos Palos CDP","abbrev":"southdospaloscdp"},
      {"name":"South Monrovia Island CDP","abbrev":"southmonroviaislandcdp"},
      {"name":"South Oroville CDP","abbrev":"southorovillecdp"},
      {"name":"South San Gabriel CDP","abbrev":"southsangabrielcdp"},
      {"name":"South San Jose Hills CDP","abbrev":"southsanjosehillscdp"},
      {"name":"South Taft CDP","abbrev":"southtaftcdp"},
      {"name":"South Whittier CDP","abbrev":"southwhittiercdp"},
      {"name":"Spaulding CDP","abbrev":"spauldingcdp"},
      {"name":"Spreckels CDP","abbrev":"spreckelscdp"},
      {"name":"Spring Garden CDP","abbrev":"springgardencdp"},
      {"name":"Spring Valley CDP","abbrev":"springvalleycdp"},
      {"name":"Spring Valley CDP","abbrev":"springvalleycdp"},
      {"name":"Spring Valley Lake CDP","abbrev":"springvalleylakecdp"},
      {"name":"Springville CDP","abbrev":"springvillecdp"},
      {"name":"Squaw Valley CDP","abbrev":"squawvalleycdp"},
      {"name":"Squirrel Mountain Valley CDP","abbrev":"squirrelmountainvalleycdp"},
      {"name":"Stallion Springs CDP","abbrev":"stallionspringscdp"},
      {"name":"Stanford CDP","abbrev":"stanfordcdp"},
      {"name":"Stevenson Ranch CDP","abbrev":"stevensonranchcdp"},
      {"name":"Stevinson CDP","abbrev":"stevinsoncdp"},
      {"name":"Stinson Beach CDP","abbrev":"stinsonbeachcdp"},
      {"name":"Stirling City CDP","abbrev":"stirlingcitycdp"},
      {"name":"Stonyford CDP","abbrev":"stonyfordcdp"},
      {"name":"Storrie CDP","abbrev":"storriecdp"},
      {"name":"Stratford CDP","abbrev":"stratfordcdp"},
      {"name":"Strathmore CDP","abbrev":"strathmorecdp"},
      {"name":"Strawberry CDP","abbrev":"strawberrycdp"},
      {"name":"Strawberry CDP","abbrev":"strawberrycdp"},
      {"name":"Sugarloaf Mountain Park CDP","abbrev":"sugarloafmountainparkcdp"},
      {"name":"Sugarloaf Saw Mill CDP","abbrev":"sugarloafsawmillcdp"},
      {"name":"Sugarloaf Village CDP","abbrev":"sugarloafvillagecdp"},
      {"name":"Sultana CDP","abbrev":"sultanacdp"},
      {"name":"Summerland CDP","abbrev":"summerlandcdp"},
      {"name":"Sunnyside CDP","abbrev":"sunnysidecdp"},
      {"name":"Sunnyside-Tahoe City CDP","abbrev":"sunnyside-tahoecitycdp"},
      {"name":"Sunny Slopes CDP","abbrev":"sunnyslopescdp"},
      {"name":"Sunol CDP","abbrev":"sunolcdp"},
      {"name":"Sun Village CDP","abbrev":"sunvillagecdp"},
      {"name":"Sutter CDP","abbrev":"suttercdp"},
      {"name":"Swall Meadows CDP","abbrev":"swallmeadowscdp"},
      {"name":"Taft Heights CDP","abbrev":"taftheightscdp"},
      {"name":"Taft Mosswood CDP","abbrev":"taftmosswoodcdp"},
      {"name":"Tahoe Vista CDP","abbrev":"tahoevistacdp"},
      {"name":"Tahoma CDP","abbrev":"tahomacdp"},
      {"name":"Talmage CDP","abbrev":"talmagecdp"},
      {"name":"Tamalpais-Homestead Valley CDP","abbrev":"tamalpais-homesteadvalleycdp"},
      {"name":"Tara Hills CDP","abbrev":"tarahillscdp"},
      {"name":"Tarpey Village CDP","abbrev":"tarpeyvillagecdp"},
      {"name":"Taylorsville CDP","abbrev":"taylorsvillecdp"},
      {"name":"Tecopa CDP","abbrev":"tecopacdp"},
      {"name":"Temelec CDP","abbrev":"temeleccdp"},
      {"name":"Temescal Valley CDP","abbrev":"temescalvalleycdp"},
      {"name":"Templeton CDP","abbrev":"templetoncdp"},
      {"name":"Tennant CDP","abbrev":"tennantcdp"},
      {"name":"Terminous CDP","abbrev":"terminouscdp"},
      {"name":"Terra Bella CDP","abbrev":"terrabellacdp"},
      {"name":"Teviston CDP","abbrev":"tevistoncdp"},
      {"name":"Thermal CDP","abbrev":"thermalcdp"},
      {"name":"Thermalito CDP","abbrev":"thermalitocdp"},
      {"name":"Thornton CDP","abbrev":"thorntoncdp"},
      {"name":"Thousand Palms CDP","abbrev":"thousandpalmscdp"},
      {"name":"Three Rivers CDP","abbrev":"threeriverscdp"},
      {"name":"Three Rocks CDP","abbrev":"threerockscdp"},
      {"name":"Timber Cove CDP","abbrev":"timbercovecdp"},
      {"name":"Tipton CDP","abbrev":"tiptoncdp"},
      {"name":"Tobin CDP","abbrev":"tobincdp"},
      {"name":"Tomales CDP","abbrev":"tomalescdp"},
      {"name":"Tonyville CDP","abbrev":"tonyvillecdp"},
      {"name":"Tooleville CDP","abbrev":"toolevillecdp"},
      {"name":"Topanga CDP","abbrev":"topangacdp"},
      {"name":"Topaz CDP","abbrev":"topazcdp"},
      {"name":"Toro Canyon CDP","abbrev":"torocanyoncdp"},
      {"name":"Tranquillity CDP","abbrev":"tranquillitycdp"},
      {"name":"Traver CDP","abbrev":"travercdp"},
      {"name":"Tres Pinos CDP","abbrev":"trespinoscdp"},
      {"name":"Trinity Center CDP","abbrev":"trinitycentercdp"},
      {"name":"Trinity Village CDP","abbrev":"trinityvillagecdp"},
      {"name":"Trona CDP","abbrev":"tronacdp"},
      {"name":"Trowbridge CDP","abbrev":"trowbridgecdp"},
      {"name":"Tuolumne City CDP","abbrev":"tuolumnecitycdp"},
      {"name":"Tupman CDP","abbrev":"tupmancdp"},
      {"name":"Tuttle CDP","abbrev":"tuttlecdp"},
      {"name":"Tuttletown CDP","abbrev":"tuttletowncdp"},
      {"name":"Twain CDP","abbrev":"twaincdp"},
      {"name":"Twain Harte CDP","abbrev":"twainhartecdp"},
      {"name":"Twin Lakes CDP","abbrev":"twinlakescdp"},
      {"name":"University of California Davis CDP","abbrev":"universityofcaliforniadaviscdp"},
      {"name":"University of California Merced CDP","abbrev":"universityofcaliforniamercedcdp"},
      {"name":"Upper Lake CDP","abbrev":"upperlakecdp"},
      {"name":"Valinda CDP","abbrev":"valindacdp"},
      {"name":"Vallecito CDP","abbrev":"vallecitocdp"},
      {"name":"Valle Vista CDP","abbrev":"vallevistacdp"},
      {"name":"Valley Acres CDP","abbrev":"valleyacrescdp"},
      {"name":"Valley Center CDP","abbrev":"valleycentercdp"},
      {"name":"Valley Ford CDP","abbrev":"valleyfordcdp"},
      {"name":"Valley Home CDP","abbrev":"valleyhomecdp"},
      {"name":"Valley Ranch CDP","abbrev":"valleyranchcdp"},
      {"name":"Valley Springs CDP","abbrev":"valleyspringscdp"},
      {"name":"Valley Wells CDP","abbrev":"valleywellscdp"},
      {"name":"Val Verde CDP","abbrev":"valverdecdp"},
      {"name":"Vandenberg AFB CDP","abbrev":"vandenbergafbcdp"},
      {"name":"Vandenberg Village CDP","abbrev":"vandenbergvillagecdp"},
      {"name":"Verdi CDP","abbrev":"verdicdp"},
      {"name":"Victor CDP","abbrev":"victorcdp"},
      {"name":"View Park-Windsor Hills CDP","abbrev":"viewpark-windsorhillscdp"},
      {"name":"Vina CDP","abbrev":"vinacdp"},
      {"name":"Vincent CDP","abbrev":"vincentcdp"},
      {"name":"Vine Hill CDP","abbrev":"vinehillcdp"},
      {"name":"Vineyard CDP","abbrev":"vineyardcdp"},
      {"name":"Vista Santa Rosa CDP","abbrev":"vistasantarosacdp"},
      {"name":"Volcano CDP","abbrev":"volcanocdp"},
      {"name":"Volta CDP","abbrev":"voltacdp"},
      {"name":"Walker CDP","abbrev":"walkercdp"},
      {"name":"Wallace CDP","abbrev":"wallacecdp"},
      {"name":"Walnut Grove CDP","abbrev":"walnutgrovecdp"},
      {"name":"Walnut Park CDP","abbrev":"walnutparkcdp"},
      {"name":"Warm Springs CDP","abbrev":"warmspringscdp"},
      {"name":"Warner Valley CDP","abbrev":"warnervalleycdp"},
      {"name":"Washington CDP","abbrev":"washingtoncdp"},
      {"name":"Waterloo CDP","abbrev":"waterloocdp"},
      {"name":"Waukena CDP","abbrev":"waukenacdp"},
      {"name":"Wawona CDP","abbrev":"wawonacdp"},
      {"name":"Weaverville CDP","abbrev":"weavervillecdp"},
      {"name":"Weedpatch CDP","abbrev":"weedpatchcdp"},
      {"name":"Weldon CDP","abbrev":"weldoncdp"},
      {"name":"Weott CDP","abbrev":"weottcdp"},
      {"name":"West Athens CDP","abbrev":"westathenscdp"},
      {"name":"West Bishop CDP","abbrev":"westbishopcdp"},
      {"name":"West Carson CDP","abbrev":"westcarsoncdp"},
      {"name":"West Goshen CDP","abbrev":"westgoshencdp"},
      {"name":"Westhaven-Moonstone CDP","abbrev":"westhaven-moonstonecdp"},
      {"name":"Westley CDP","abbrev":"westleycdp"},
      {"name":"West Menlo Park CDP","abbrev":"westmenloparkcdp"},
      {"name":"West Modesto CDP","abbrev":"westmodestocdp"},
      {"name":"Westmont CDP","abbrev":"westmontcdp"},
      {"name":"West Park CDP","abbrev":"westparkcdp"},
      {"name":"West Point CDP","abbrev":"westpointcdp"},
      {"name":"West Puente Valley CDP","abbrev":"westpuentevalleycdp"},
      {"name":"West Rancho Dominguez CDP","abbrev":"westranchodominguezcdp"},
      {"name":"West Whittier-Los Nietos CDP","abbrev":"westwhittier-losnietoscdp"},
      {"name":"Westwood CDP","abbrev":"westwoodcdp"},
      {"name":"Whitehawk CDP","abbrev":"whitehawkcdp"},
      {"name":"Whitewater CDP","abbrev":"whitewatercdp"},
      {"name":"Whitley Gardens CDP","abbrev":"whitleygardenscdp"},
      {"name":"Wilkerson CDP","abbrev":"wilkersoncdp"},
      {"name":"Willowbrook CDP","abbrev":"willowbrookcdp"},
      {"name":"Willow Creek CDP","abbrev":"willowcreekcdp"},
      {"name":"Wilsonia CDP","abbrev":"wilsoniacdp"},
      {"name":"Wilton CDP","abbrev":"wiltoncdp"},
      {"name":"Winchester CDP","abbrev":"winchestercdp"},
      {"name":"Winter Gardens CDP","abbrev":"wintergardenscdp"},
      {"name":"Winterhaven CDP","abbrev":"winterhavencdp"},
      {"name":"Winton CDP","abbrev":"wintoncdp"},
      {"name":"Wofford Heights CDP","abbrev":"woffordheightscdp"},
      {"name":"Woodacre CDP","abbrev":"woodacrecdp"},
      {"name":"Woodbridge CDP","abbrev":"woodbridgecdp"},
      {"name":"Woodcrest CDP","abbrev":"woodcrestcdp"},
      {"name":"Woodlands CDP","abbrev":"woodlandscdp"},
      {"name":"Woodville CDP","abbrev":"woodvillecdp"},
      {"name":"Wrightwood CDP","abbrev":"wrightwoodcdp"},
      {"name":"Yankee Hill CDP","abbrev":"yankeehillcdp"},
      {"name":"Yettem CDP","abbrev":"yettemcdp"},
      {"name":"Yolo CDP","abbrev":"yolocdp"},
      {"name":"Yosemite Lakes CDP","abbrev":"yosemitelakescdp"},
      {"name":"Yosemite Valley CDP","abbrev":"yosemitevalleycdp"},
      {"name":"Zayante CDP","abbrev":"zayantecdp"}
    ]
    }
  ]
};
