window.meta = {
  "states": [
    {"name":"Alaska","type":"state","country":"usa"},
    {"name":"Alabama","type":"state","country":"usa"},
    {"name":"Arkansas","type":"state","country":"usa"},
    {"name":"Arizona","type":"state","country":"usa"},
    {"name":"California","type":"state","country":"usa"},
    {"name":"Colorado","type":"state","country":"usa"},
    {"name":"Connecticut","type":"state","country":"usa"},
    {"name":"Delaware","type":"state","country":"usa"},
    {"name":"Florida","type":"state","country":"usa"},
    {"name":"Georgia","type":"state","country":"usa"},
    {"name":"Hawaii","type":"state","country":"usa"},
    {"name":"Iowa","type":"state","country":"usa"},
    {"name":"Idaho","type":"state","country":"usa"},
    {"name":"Illinois","type":"state","country":"usa"},
    {"name":"Indiana","type":"state","country":"usa"},
    {"name":"Kansas","type":"state","country":"usa"},
    {"name":"Kentucky","type":"state","country":"usa"},
    {"name":"Louisiana","type":"state","country":"usa"},
    {"name":"Massachusetts","type":"state","country":"usa"},
    {"name":"Maryland","type":"state","country":"usa"},
    {"name":"Maine","type":"state","country":"usa"},
    {"name":"Michigan","type":"state","country":"usa"},
    {"name":"Minnesota","type":"state","country":"usa"},
    {"name":"Missouri","type":"state","country":"usa"},
    {"name":"Mississippi","type":"state","country":"usa"},
    {"name":"Montana","type":"state","country":"usa"},
    {"name":"North Carolina","type":"state","country":"usa"},
    {"name":"North Dakota","type":"state","country":"usa"},
    {"name":"Nebraska","type":"state","country":"usa"},
    {"name":"New Hampshire","type":"state","country":"usa"},
    {"name":"New Jersey","type":"state","country":"usa"},
    {"name":"New Mexico","type":"state","country":"usa"},
    {"name":"Nevada","type":"state","country":"usa"},
    {"name":"New York","type":"state","country":"usa"},
    {"name":"Ohio","type":"state","country":"usa"},
    {"name":"Oklahoma","type":"state","country":"usa"},
    {"name":"Oregon","type":"state","country":"usa"},
    {"name":"Pennsylvania","type":"state","country":"usa"},
    {"name":"Rhode Island","type":"state","country":"usa"},
    {"name":"South Carolina","type":"state","country":"usa"},
    {"name":"South Dakota","type":"state","country":"usa"},
    {"name":"Tennessee","type":"state","country":"usa"},
    {"name":"Texas","type":"state","country":"usa"},
    {"name":"Utah","type":"state","country":"usa"},
    {"name":"Virginia","type":"state","country":"usa"},
    {"name":"Vermont","type":"state","country":"usa"},
    {"name":"Washington","type":"state","country":"usa"},
    {"name":"Wisconsin","type":"state","country":"usa"},
    {"name":"West Virginia","type":"state","country":"usa"},
    {"name":"Wyoming","type":"state","country":"usa"}
  ],
  "countries": [
    {"name":"Afghanistan","abbrev":"afg","type":"country"},
    {"name":"Angola","abbrev":"ang","type":"country"},
    {"name":"Albania","abbrev":"alb","type":"country"},
    {"name":"Andorra","abbrev":"and","type":"country"},
    {"name":"United Arab Emirates","abbrev":"uae","type":"country"},
    {"name":"Argentina","abbrev":"arg","type":"country"},
    {"name":"Armenia","abbrev":"arm","type":"country"},
    {"name":"Antarctica","abbrev":"ant","type":"country"},
    {"name":"Antigua and Barb.","abbrev":"antb","type":"country"},
    {"name":"Australia","abbrev":"auz","type":"country"},
    {"name":"Austria","abbrev":"aust","type":"country"},
    {"name":"Azerbaijan","abbrev":"aze","type":"country"},
    {"name":"Burundi","abbrev":"bur","type":"country"},
    {"name":"Belgium","abbrev":"belg","type":"country"},
    {"name":"Benin","abbrev":"benin","type":"country"},
    {"name":"Burkina Faso","abbrev":"bf","type":"country"},
    {"name":"Bangladesh","abbrev":"bang","type":"country"},
    {"name":"Bulgaria","abbrev":"bulg","type":"country"},
    {"name":"Bahrain","abbrev":"bahr","type":"country"},
    {"name":"Bahamas","abbrev":"bhs","type":"country"},
    {"name":"Bosnia and Herz.","abbrev":"bh","type":"country"},
    {"name":"Bajo Nuevo Bank (Petrel Is.)","abbrev":"bjn","type":"country"},
    {"name":"Belarus","abbrev":"bela","type":"country"},
    {"name":"Belize","abbrev":"belize","type":"country"},
    {"name":"Bolivia","abbrev":"bolivia","type":"country"},
    {"name":"Brazil","abbrev":"brazil","type":"country"},
    {"name":"Barbados","abbrev":"barb","type":"country"},
    {"name":"Brunei","abbrev":"brunei","type":"country"},
    {"name":"Bhutan","abbrev":"bhutan","type":"country"},
    {"name":"Botswana","abbrev":"bwa","type":"country"},
    {"name":"Central African Rep.","abbrev":"car","type":"country"},
    {"name":"Canada","abbrev":"can","type":"country"},
    {"name":"China","abbrev":"china","type":"country"},
    {"name":"Switzerland","abbrev":"switz","type":"country"},
    {"name":"Chile","abbrev":"chile","type":"country"},
    {"name":"Côte d'Ivoire","abbrev":"ic","type":"country"},
    {"name":"Cameroon","abbrev":"cam","type":"country"},
    {"name":"Cyprus U.N. Buffer Zone","abbrev":"cnm","type":"country"},
    {"name":"Democratic Republic of the Congo","abbrev":"drc","type":"country"},
    {"name":"Republic of Congo","abbrev":"repcongo","type":"country"},
    {"name":"Colombia","abbrev":"col","type":"country"},
    {"name":"Comoros","abbrev":"com","type":"country"},
    {"name":"Cape Verde","abbrev":"cvd","type":"country"},
    {"name":"Costa Rica","abbrev":"cr","type":"country"},
    {"name":"Cuba","abbrev":"cuba","type":"country"},
    {"name":"N. Cyprus","abbrev":"ncy","type":"country"},
    {"name":"Cyprus","abbrev":"cyp","type":"country"},
    {"name":"Czech Rep.","abbrev":"czrep","type":"country"},
    {"name":"Germany","abbrev":"ger","type":"country"},
    {"name":"Djibouti","abbrev":"dji","type":"country"},
    {"name":"Dominica","abbrev":"dinca","type":"country"},
    {"name":"Denmark","abbrev":"den","type":"country"},
    {"name":"Dominican Rep.","abbrev":"domrep","type":"country"},
    {"name":"Algeria","abbrev":"alg","type":"country"},
    {"name":"Ecuador","abbrev":"ecu","type":"country"},
    {"name":"Egypt","abbrev":"egypt","type":"country"},
    {"name":"Eritrea","abbrev":"erit","type":"country"},
    {"name":"Spain","abbrev":"sp","type":"country"},
    {"name":"Estonia","abbrev":"est","type":"country"},
    {"name":"Ethiopia","abbrev":"eth","type":"country"},
    {"name":"Finland","abbrev":"fin","type":"country"},
    {"name":"Fiji","abbrev":"fiji","type":"country"},
    {"name":"France","abbrev":"fr","type":"country"},
    {"name":"Micronesia","abbrev":"fsm","type":"country"},
    {"name":"Gabon","abbrev":"gabon","type":"country"},
    {"name":"United Kingdom","abbrev":"uk","type":"country"},
    {"name":"Georgia","abbrev":"geo","type":"country"},
    {"name":"Ghana","abbrev":"ghana","type":"country"},
    {"name":"Guinea","abbrev":"gin","type":"country"},
    {"name":"Gambia","abbrev":"gambia","type":"country"},
    {"name":"Guinea-Bissau","abbrev":"gnb","type":"country"},
    {"name":"Eq. Guinea","abbrev":"eqg","type":"country"},
    {"name":"Greece","abbrev":"greece","type":"country"},
    {"name":"Grenada","abbrev":"gren","type":"country"},
    {"name":"Guatemala","abbrev":"guat","type":"country"},
    {"name":"Guyana","abbrev":"guy","type":"country"},
    {"name":"Honduras","abbrev":"hond","type":"country"},
    {"name":"Croatia","abbrev":"cro","type":"country"},
    {"name":"Haiti","abbrev":"haiti","type":"country"},
    {"name":"Hungary","abbrev":"hun","type":"country"},
    {"name":"Indonesia","abbrev":"indo","type":"country"},
    {"name":"India","abbrev":"india","type":"country"},
    {"name":"Ireland","abbrev":"ire","type":"country"},
    {"name":"Iran","abbrev":"iran","type":"country"},
    {"name":"Iraq","abbrev":"iraq","type":"country"},
    {"name":"Israel","abbrev":"isr","type":"country"},
    {"name":"Iceland","abbrev":"iceland","type":"country"},
    {"name":"Italy","abbrev":"italy","type":"country"},
    {"name":"Jamaica","abbrev":"jam","type":"country"},
    {"name":"Jordan","abbrev":"jord","type":"country"},
    {"name":"Japan","abbrev":"japan","type":"country"},
    {"name":"Siachen Glacier","abbrev":"siachen","type":"country"},
    {"name":"Kazakhstan","abbrev":"kaz","type":"country"},
    {"name":"Kenya","abbrev":"ken","type":"country"},
    {"name":"Kyrgyzstan","abbrev":"kgz","type":"country"},
    {"name":"Cambodia","abbrev":"camb","type":"country"},
    {"name":"Kiribati","abbrev":"kir","type":"country"},
    {"name":"Saint Kitts and Nevis","abbrev":"stkn","type":"country"},
    {"name":"Republic of Korea","abbrev":"sk","type":"country"},
    {"name":"Kosovo","abbrev":"kos","type":"country"},
    {"name":"Kuwait","abbrev":"kwt","type":"country"},
    {"name":"Laos","abbrev":"laos","type":"country"},
    {"name":"Lebanon","abbrev":"leb","type":"country"},
    {"name":"Liberia","abbrev":"liberia","type":"country"},
    {"name":"Libya","abbrev":"libya","type":"country"},
    {"name":"Saint Lucia","abbrev":"sl","type":"country"},
    {"name":"Liechtenstein","abbrev":"liech","type":"country"},
    {"name":"Sri Lanka","abbrev":"sril","type":"country"},
    {"name":"Lesotho","abbrev":"les","type":"country"},
    {"name":"Lithuania","abbrev":"lith","type":"country"},
    {"name":"Luxembourg","abbrev":"lux","type":"country"},
    {"name":"Latvia","abbrev":"lat","type":"country"},
    {"name":"Morocco","abbrev":"mor","type":"country"},
    {"name":"Monaco","abbrev":"mco","type":"country"},
    {"name":"Moldova","abbrev":"mda","type":"country"},
    {"name":"Madagascar","abbrev":"mad","type":"country"},
    {"name":"Maldives","abbrev":"mald","type":"country"},
    {"name":"Mexico","abbrev":"mex","type":"country"},
    {"name":"Marshall Is.","abbrev":"mis","type":"country"},
    {"name":"Macedonia","abbrev":"mkd","type":"country"},
    {"name":"Mali","abbrev":"mali","type":"country"},
    {"name":"Malta","abbrev":"malta","type":"country"},
    {"name":"Myanmar","abbrev":"myan","type":"country"},
    {"name":"Montenegro","abbrev":"mont","type":"country"},
    {"name":"Mongolia","abbrev":"mong","type":"country"},
    {"name":"Mozambique","abbrev":"moz","type":"country"},
    {"name":"Mauritania","abbrev":"mrt","type":"country"},
    {"name":"Mauritius","abbrev":"mus","type":"country"},
    {"name":"Malawi","abbrev":"mal","type":"country"},
    {"name":"Malaysia","abbrev":"malay","type":"country"},
    {"name":"Namibia","abbrev":"nam","type":"country"},
    {"name":"Niger","abbrev":"niger","type":"country"},
    {"name":"Nigeria","abbrev":"nigeria","type":"country"},
    {"name":"Nicaragua","abbrev":"nic","type":"country"},
    {"name":"Netherlands","abbrev":"neth","type":"country"},
    {"name":"Norway","abbrev":"nor","type":"country"},
    {"name":"Nepal","abbrev":"nepal","type":"country"},
    {"name":"Nauru","abbrev":"nauru","type":"country"},
    {"name":"New Zealand","abbrev":"nz","type":"country"},
    {"name":"Oman","abbrev":"oman","type":"country"},
    {"name":"Pakistan","abbrev":"pak","type":"country"},
    {"name":"Panama","abbrev":"pan","type":"country"},
    {"name":"Peru","abbrev":"peru","type":"country"},
    {"name":"Spratly Is.","abbrev":"spratlyis","type":"country"},
    {"name":"Philippines","abbrev":"phil","type":"country"},
    {"name":"Palau","abbrev":"palau","type":"country"},
    {"name":"Papua New Guinea","abbrev":"png","type":"country"},
    {"name":"Poland","abbrev":"pol","type":"country"},
    {"name":"Dem. Rep. Korea","abbrev":"nk","type":"country"},
    {"name":"Portugal","abbrev":"port","type":"country"},
    {"name":"Paraguay","abbrev":"para","type":"country"},
    {"name":"Qatar","abbrev":"qatar","type":"country"},
    {"name":"Romania","abbrev":"rom","type":"country"},
    {"name":"Russia","abbrev":"rus","type":"country"},
    {"name":"Rwanda","abbrev":"rwa","type":"country"},
    {"name":"W. Sahara","abbrev":"wsah","type":"country"},
    {"name":"Saudi Arabia","abbrev":"saud","type":"country"},
    {"name":"Scarborough Reef","abbrev":"sr","type":"country"},
    {"name":"Sudan","abbrev":"sudan","type":"country"},
    {"name":"S. Sudan","abbrev":"ssud","type":"country"},
    {"name":"Senegal","abbrev":"sen","type":"country"},
    {"name":"Serranilla Bank","abbrev":"sb","type":"country"},
    {"name":"Singapore","abbrev":"sing","type":"country"},
    {"name":"Solomon Is.","abbrev":"sis","type":"country"},
    {"name":"Sierra Leone","abbrev":"sl","type":"country"},
    {"name":"El Salvador","abbrev":"els","type":"country"},
    {"name":"San Marino","abbrev":"sm","type":"country"},
    {"name":"Somaliland","abbrev":"solnd","type":"country"},
    {"name":"Somalia","abbrev":"som","type":"country"},
    {"name":"Serbia","abbrev":"serb","type":"country"},
    {"name":"Sao Tome and Principe","abbrev":"stp","type":"country"},
    {"name":"Suriname","abbrev":"sur","type":"country"},
    {"name":"Slovakia","abbrev":"svk","type":"country"},
    {"name":"Slovenia","abbrev":"slo","type":"country"},
    {"name":"Sweden","abbrev":"swe","type":"country"},
    {"name":"Swaziland","abbrev":"swz","type":"country"},
    {"name":"Seychelles","abbrev":"syc","type":"country"},
    {"name":"Syria","abbrev":"syria","type":"country"},
    {"name":"Chad","abbrev":"chad","type":"country"},
    {"name":"Togo","abbrev":"togo","type":"country"},
    {"name":"Thailand","abbrev":"thai","type":"country"},
    {"name":"Tajikistan","abbrev":"tjk","type":"country"},
    {"name":"Turkmenistan","abbrev":"turkm","type":"country"},
    {"name":"Timor-Leste","abbrev":"tl","type":"country"},
    {"name":"Tonga","abbrev":"tongo","type":"country"},
    {"name":"Trinidad and Tobago","abbrev":"trt","type":"country"},
    {"name":"Tunisia","abbrev":"tun","type":"country"},
    {"name":"Turkey","abbrev":"tur","type":"country"},
    {"name":"Tuvalu","abbrev":"tuv","type":"country"},
    {"name":"Taiwan","abbrev":"taiwan","type":"country"},
    {"name":"Tanzania","abbrev":"tanz","type":"country"},
    {"name":"Uganda","abbrev":"uga","type":"country"},
    {"name":"Ukraine","abbrev":"ukr","type":"country"},
    {"name":"Uruguay","abbrev":"ury","type":"country"},
    {"name":"United States","abbrev":"usa","type":"country"},
    {"name":"Uzbekistan","abbrev":"uzb","type":"country"},
    {"name":"Vatican","abbrev":"vat","type":"country"},
    {"name":"St. Vin. and Gren.","abbrev":"stvg","type":"country"},
    {"name":"Venezuela","abbrev":"ven","type":"country"},
    {"name":"Vietnam","abbrev":"viet","type":"country"},
    {"name":"Vanuatu","abbrev":"van","type":"country"},
    {"name":"Samoa","abbrev":"samoa","type":"country"},
    {"name":"Yemen","abbrev":"yem","type":"country"},
    {"name":"South Africa","abbrev":"saf","type":"country"},
    {"name":"Zambia","abbrev":"zambia","type":"country"},
    {"name":"Zimbabwe","abbrev":"zimb","type":"country"}
  ]
}
